yast/yast-installation

package/yast2-installation.changes, package/yast2-installation.spec
fixing a failure in openqa, see https://github.com/yast/yast-yast2/pull/325#issuecomment-71190413
=> release the last two changes

package/yast2-installation.changes, package/yast2-installation.spec, src/clients/inst_complex_welcome.rb
case of live installation (bnc#904103)
=> ensure the langugages value is set and Solver is run in

package/yast2-installation.changes, package/yast2-installation.spec, startup/YaST2.call
- 3.1.130
Port #267 to `master`
=> Support custom display number in "display_ip" boot option (bnc#913888)

package/yast2-installation.changes, package/yast2-installation.spec, src/include/installation/inst_inc_all.rb
=> Removed redundant initialization label (bnc#878538)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
fix crashing proposal_runner in offline update ( happen only in if condition for normal stage and update mode ). So it affects only new yast2-migration module.
=> Fix runner

package/yast2-installation.changes, package/yast2-installation.spec
This is a port of #281 to master
=> Always enable startup scripts - also in master

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec, startup/Second-Stage/S09-cleanup, startup/YaST2.call, startup/common/misc.sh
Makes possible to run VNC during second stage
=> Manage the conflict between xinetd and Xvnc

doc/installation_overview.md
This is a draft of a document describing (without going in-depth) the installation process. Sure it has a lot of obvious things but maybe it could be useful for newcomers.
=> Add a document describing the installation workflow

package/yast2-installation.changes, package/yast2-installation.spec, src/Makefile.am, src/clients/inst_finish.rb, src/clients/snapshots_finish.rb, src/lib/installation/snapshots_finish.rb, test/Makefile.am, test/snapshots_finish_test.rb
Moved snapshots_client from yast-storage.
=> Add snapshots_finish client

package/yast2-installation.changes
- SLE-checker doesn't like space between FATE and it's number
=> Correcting changelog

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
=> Fixed menu button label in the proposal (bsc#936427)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_store.rb, test/proposal_store_test.rb
- Handling values returned from Description and MakeProposal were messed up, especially in test-cases
- bsc#936448
=> Fixed handling user request to change a proposal

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb, test/snapshots_finish_test.rb
=> Huha snapshot cleanup

package/yast2-installation.changes, package/yast2-installation.spec, src/Makefile.am
Fixing #298 which omitted the new files, causing https://openqa.suse.de/tests/102837
=> Do install the new files; mention the move in .changes.

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
* 304b40f packaging
* a5e309c ignore failed plymouth
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_150811_ignore_plymouth_return'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/cio_ignore.rb, test/cio_ignore_test.rb, test/installation_misc_test.rb, test/test_helper.rb
* 8719626 packaging
* 39c2aac added new flag for cio_ignore in autoyast
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_150813_cio_ignore'

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
This is a backport of 
https://github.com/yast/yast-installation/pull/305/files
=> ignoring return value of plymouth

package/yast2-installation.changes, package/yast2-installation.spec, test/cio_ignore_test.rb
* 18767bf packaging
* 4a58c34 fixed cio_ignore testcase
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_150825_fixed_testcases'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb
- bsc#943746, bsc#944035
- P1!
- Setting language/languages was using wrong data type string vs array
=> Fix languages during upgrade

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb
=> Fix keyboard selection when changing language (bnc#947969)

doc/control-file.md
- Added documentation about `packages` in `supported_desktops` (bsc#866724 and boo#951558)
- Marked all XML as XML
=> Control file documentation

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
[bsc#935965](https://bugzilla.suse.com/show_bug.cgi?id=935965)
=> Don't let getty kill YaST with SIGHUP on serial console (bsc#935965).

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_deploy_image.rb
(bsc#956325, bsc#910728)
...when deploying installation images
- 3.1.163
See https://github.com/yast/yast-autoinstallation/pull/168
=> Save the software selection for using it later in AutoYaST 

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
Merge #323 (from SLE12-GA) into the SP1 codebase
=> Don't let getty kill YaST on further serial consoles (bsc#935965) SP1

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_store.rb, test/proposal_store_test.rb
Merges the original fix #323.
Actually this is a merge of the whole after-SP1 branch so it includes #326 too.
=> Don't let getty kill YaST on further serial consoles (bsc#935965) master

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
* f468030 packaging
* db898ea removed dependencies for network
* ed01da3 ifconfig is obsolete
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_151217_cleanup_service_dependencies'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/network_finish.rb
=> Dropped network service setup

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec
Merging pull request #337 into SP1
=> Merge to SP1

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec
=> Last merging step

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
the list is provided e.g. when starting second stage of ssh AY installation
bnc#956473
=> Improved network interfaces listing

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
https://github.com/yast/yast-installation/pull/342
=> Merged SLE-12 branch

.travis.yml, src/lib/installation/clients/inst_complex_welcome.rb, test/inst_complex_welcome_test.rb
* I continued work done in #319 by @jreidinger moving code to src/lib and adding tests.
* The behaviour was probed also in yast/yast-registration#249
=> Adding recover values behaviour (fate#319716)

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
https://github.com/yast/yast-installation/pull/361
=> Improved network interfaces listing (SLE-12-GA)

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
See https://github.com/yast/yast-installation/pull/363 and https://github.com/yast/yast-installation/pull/361
=> Improved network interfaces listing (SLE-12-SP2)

doc/SELF_UPDATE.md
- includes some minor formatting/wording fixes
=> Document the update repo URL evaluation during self-update

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb, test/inst_complex_welcome_test.rb, test/test_helper.rb
This PR fixes [bsc#975774](https://bugzilla.suse.com/show_bug.cgi?id=975774). BTW, I did some minor refactoring.
Manually tested.
=> Fix license acceptance

doc/SELF_UPDATE.md
the correct name of the section in the AY profile is "general"
=> SELF_UPDATE.md - fixed the AY profile specification

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_pre_install.rb
See comment on https://fate.suse.com/319624
This goes together with https://github.com/yast/yast-users/pull/98
=> pre_install: cache users in UsersDatabase

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/select_system_role.rb
Do not merge yet, needs to be done in sync with https://github.com/yast/skelcd-control-SLES/pull/58
=> get more texts for roles dialog from control file, allow a general label (bsc#974625)

.gitignore, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb
... by the window manager close button in SSH installation
- 3.1.186
=> handle closing the initial installation screen (bsc#979499)

package/yast2-installation.changes, src/lib/installation/clients/ssh_import_proposal.rb
The version increase will be already forced by #375 today or tomorrow.
=> SSH import proposal summary: use bullet point

package/yast2-installation.changes, package/yast2-installation.spec
I completely forgot to add changes and update the version... :flushed:
=> version update

package/yast2-installation.changes, src/lib/installation/ssh_config.rb, test/fixtures/root1/etc/ssh/backup/README, test/ssh_config_test.rb
Fixes [bsc#982522](https://bugzilla.suse.com/show_bug.cgi?id=982522). No version number bump as I plan to merge with #388.
=> SshConfig will only consider regular files

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec
It should fix [bsc#980365](https://bugzilla.suse.com/show_bug.cgi?id=980365).
=> YaST2-Firstboot should run after YaST2-Second-Stage

doc/SELF_UPDATE.md
https://trello.com/c/SWxjqjos
https://fate.suse.com/319716
=> Documented the pattern for actual self_update_url values (FATE#319716).

SUBDIRS, doc/Makefile.am, doc/autodocs/Makefile.am, package/yast2-installation.changes, package/yast2-installation.spec
Drop yast2-installation-devel-doc package ([fate#320356](https://fate.suse.com/320356)).
=> Drop yast2-installation-devel-doc package

package/yast2-installation.changes, package/yast2-installation.spec, src/Makefile.am, src/autoyast-rnc/ssh_import.rnc
* 4ed2796 added ssh_import.rnc
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_160712_added_autoyast_schema_file'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb
Goes together with https://github.com/yast/yast-storage/pull/217
=> Don't ask twice about multipath bsc#989770

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_extrasources.rb, test/Makefile.am, test/inst_extrasources_test.rb
manual testing in process now.
=> Twice url fix

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb, src/lib/installation/clients/inst_disks_activate.rb, test/inst_complex_welcome_test.rb, test/inst_disks_activate_test.rb
Tested update_installer manually in a normal installation and with it just after inst_dhcp client in the control.xml file.
=> Remove fixes for update installer not needed anymore.

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/select_system_role.rb
#426 cannot be merged because of a conflict, this is just a copy of #426 with merged changes from `master`.
=> Resolve conflicts in PR#426

CONTRIBUTING.md, doc/SELF_UPDATE.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_complex_welcome.rb, src/lib/installation/clients/inst_disks_activate.rb, src/lib/installation/clients/inst_update_installer.rb, src/lib/installation/update_repository.rb, test/inst_complex_welcome_test.rb, test/inst_disks_activate_test.rb, test/inst_finish_test.rb, test/inst_update_installer_test.rb, test/test_helper.rb, test/update_repository_test.rb
Improvements:
- Initialize the package management so it does not depend on the previous installation steps
- Show progress while downloading the packages
See also the [related change](https://github.com/yast/skelcd-control-SLES/pull/71) in the `control.xml`.
=> Self update refactoring

package/yast2-installation.changes
Minor fix to changes file to match package's version.
=> Fix version number in changes file

package/yast2-installation.changes
=> Fix changes version sle12 sp2

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_store.rb, test/proposal_store_test.rb
[bsc#994127](https://bugzilla.suse.com/show_bug.cgi?id=994127)
=> Proposal store fix

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_store.rb, test/proposal_store_test.rb
* ec091a9 bnc_999953; fixed crash in showing proposal
* e3637b7 bnc_999953; fixed crash in showing proposal (#437)
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_160921_bnc_999953'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb
Translate description of Snapper snapshots according to the [solution proposed](https://bugzilla.suse.com/show_bug.cgi?id=988700#c5) by @mvidner to bsc#988700.
=> Translate snapper snapshots

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb
Merge `SLE-12-SP2` branch to include fix for [bsc#988700](https://bugzilla.suse.com/show_bug.cgi?id=988700).
=> Merge SLE-12-SP2 branch

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb
* cc3f179 merged with merge_after_SP2_release
* 151ad12 setting popup timeout in autoyast upgrade mode (#443)
* 5d016df Translate snapper snapshots (#441)
* e3637b7 bnc_999953; fixed crash in showing proposal (#437)
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_161006_setting_popup_timeout_in_autoyast_upgrade'

package/yast2-installation.spec
Latest version in changes file is 3.2.3. I guess some merge went wrong :)
=> Fix version number in spec file

package/yast2-installation.changes
Trying to make automatic reviewers happy.
=> Fix changelog to include bsc entries

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/misc.sh
=> Safer logging

src/lib/installation/clients/umount_finish.rb
For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.
=> - disable some non-working code

README.md, doc/control-file.md, doc/installation_clients.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, src/lib/installation/proposal_store.rb, test/proposal_store_test.rb
This is just a `CASP` -> `master` merge, it has been already reviewed.
=> Merge CASP branch to master

doc/control-file.md
- Updated the proposal part
- Removed the Automatic Configuration part (not used anymore, the seconds stage has been dropped completely)
- Updated self-update documentation
For better review you can check the [rendered version](https://github.com/yast/yast-installation/blob/012e83131b4a1e129140c253aae2f5ca5af21b81/doc/control-file.md#proposals).
=> Updated the control file documentation

doc/SELF_UPDATE.md
Document the fact that self-update is now disabled by default.
=> Document that self-update is disabled by default

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb
Merge `merge_after_SP2_release` branch into `SLE-12-SP2`.
=> SLE 12 SP2 merge

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, test/proposal_runner_test.rb
Fix for [bsc#1013976](https://bugzilla.suse.com/show_bug.cgi?id=1013976).
=> Bsc 1013976

autoyast_desktop/ssh_import.desktop, doc/SELF_UPDATE.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, test/proposal_runner_test.rb
Merge #471 into the `SLE-12-SP2-CASP` branch.
=> bsc#1013976 in CASP

package/yast2-installation.changes, package/yast2-installation.spec, src/Makefile.am, src/clients/inst_worker_role.rb, src/lib/installation/dialogs/worker_role.rb
Trello card: https://trello.com/c/OFmpN4xq/785-5-casp-role-specific-dialog
By now it just write the log file when going next.
=> New worker role dialog.

doc/control-file.md
See https://github.com/yast/yast-packager/pull/212 and https://github.com/yast/yast-installation-control/pull/35.
=> Add documentation for minimalistic_libzypp_config option

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, src/lib/installation/proposal_store.rb, test/proposal_runner_test.rb, test/proposal_store_test.rb
This PR merges #489 and #483 into `master` branch.
=> Add minimalistic libzypp config master

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_download_release_notes.rb, src/modules/InstData.rb, test/lib/inst_download_release_notes_test.rb
Fixes [bsc#1015794](https://bugzilla.suse.com/show_bug.cgi?id=1015794).
=> Do not retry release notes download after getting a 4xx

src/lib/installation/widgets/mocked.rb
Use the new network proposal added in yast/yast-network#491
=> Use network proposal

package/yast2-installation.spec
version bump and changes not needed, as it do not build on jenkins
=> fix build dependencies

test/inst_casp_overview_test.rb
Mock also PasswordWidget, KeyboardSelectionCombo
=> Make Travis Green

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_casp_overview.rb, test/inst_casp_overview_test.rb
https://trello.com/c/XDgl2dj7/816-13-casp-new-all-in-one-dialog
https://fate.suse.com/322328
Main PR: https://github.com/yast/yast-installation/pull/487
=> Added installation confirmation to all-in-one-dialog (FATE#322328)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_casp_overview.rb, test/inst_casp_overview_test.rb
tested manually
https://fate.suse.com/321738
=> Casp services

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_casp_overview.rb, src/lib/installation/widgets/overview.rb, test/inst_casp_overview_test.rb
[bsc#1022546](https://bugzilla.suse.com/show_bug.cgi?id=1022546)
=> [RFC] Do not reset all-in-one dialog when sub dialog is closed

test/lib/update_repositories_finder_test.rb
Fix build problems in non-x86_64 architectures.
=> Fix UpdateRepositoriesFinder tests for non-x86_64 archs

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_casp_overview.rb
done together with Ken
both reviewed by Ken
=> UI / UX changes in all in one dialog

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/system_role.rb, test/lib/widgets/system_role_reader_test.rb
Fixes [bsc#1029312](https://bugzilla.suse.com/show_bug.cgi?id=1029312). BTW, it add some unit tests to the SystemRoleReader module.
=> Fix system role help

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/overview.rb, test/Makefile.am, test/widgets_overview_test.rb
[bsc#1029291](https://bugzilla.suse.com/show_bug.cgi?id=1029291)
=> Allow proceeding after a blocking condition has been fixed

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/overview.rb, test/widgets_overview_test.rb
forward port of #538 
[bsc#1029291](https://bugzilla.suse.com/show_bug.cgi?id=1029291)
=> Allow proceeding after a blocking condition has been fixed (master)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/system_role.rb
Now it looks like this
http://paste.opensuse.org/images/89499036.png
=> Extra spacing in the openSUSE role selection dialog

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/update_repository.rb, test/update_repository_test.rb
Use the shared functionality also in the self-update code.
- 3.2.33
=> Use the shared package download and extraction from FATE#320772

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/system_role.rb
[bsc#1032057](https://bugzilla.suse.com/show_bug.cgi?id=1032057)
=> Renamed Controller Node to Administration Node (bsc#1032057).

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/widgets/system_role.rb
[bsc#1032057](https://bugzilla.suse.com/show_bug.cgi?id=1032057)
=> Renamed Controller Node to Administration Node (master)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_disks_activate.rb, test/inst_disks_activate_test.rb
For https://trello.com/c/nxgcriYy/612-2-storageng-fix-instdisksactivate-client.
=> adapted re-probing to storage-ng

package/yast2-installation.spec
I forgot to update the version in the previous PR... :flushed:
=> Update the version

Dockerfile, Rakefile
- Merge the SP3 branch to master
- Revert the SP3 specific changes
=> Merge the SP3 branch

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
_This is just merging that commit from the SLE-12-SP3-CASP branch to master_
Original PR: https://github.com/yast/yast-installation/pull/575
=> Enable using home partition as generic separate data partition

package/yast2-installation.changes
Update changes file to reflect the removal of CaaSP specific code.
=> Update changes file

package/yast2-installation.changes, package/yast2-installation.spec, src/clients/desktop_finish.rb, src/lib/installation/clients/desktop_finish.rb, test/desktop_finish_test.rb
more then just a merge. Code improved and tests added.
=> Desktop fix master

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
https://trello.com/c/zCKSIBHK/633-1-merge-caasp-hack-for-separate-data-partition-to-sle-12-sp3-branch
=> Merged SLE-12-SP2-CASP branch to SLE-12-SP3 branch

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_pre_install.rb, src/lib/installation/clients/inst_system_analysis.rb
This needs more manual testing (or even creating new automated tests) before being merged.
=> Adapt InstPreInstall to storage-ng

package/yast2-installation.changes, src/lib/installation/widgets/product_selector.rb, test/widgets/product_selector_test.rb
It should fix [bsc#1060252](https://bugzilla.suse.com/show_bug.cgi?id=1060252). I am not bumping the version because I plan to merge #609 pretty soon.
=> Registered product selection

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, test/proposal_runner_test.rb
* 2fd602ba AY: warning user if an remote installation is not possible
* bb3f25c9 AY: warning user if an remote installation is not possible
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_171004_bnc_1055279'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_disks_activate.rb
https://trello.com/c/DCrlDL2j/1116-2-sle-15-remove-dasdreload-call-from-yast
=> Drop dasd reload

doc/UPGRADE.md
- Documentation for https://trello.com/c/9uJlxBkH
- This is the initial version, some parts are not implemented yet, it should be updated later
=> Added "System Upgrade" documentation (doc/UPGRADE.md)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_finish.rb
- [Trello Card](https://trello.com/c/oGANpKhQ/1190-5-research-poc-replace-susefirewall2-with-firewalld)
- see yast/yast-firewall#33
=> Unification of firewall proposals and finish clients. (fate#323460)

package/yast2-installation.spec
=> Add missing BuildRequires

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/remote_finish_client.rb, test/remote_finish_test.rb
- It depends on yast/yast-network#599
=> Replace Remote module by the new y2remote/remote class

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
* 26333e5e fixed popup layouts
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_171220_popup_layout_ay'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb, test/proposal_runner_test.rb
Adapt to new API introduced by https://github.com/yast/yast-autoinstallation/pull/381.
=> Fix /tmp/profile

.travis.yml, package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
Supersedes #643 merging these changes from SLE 12 SP2.
=> Disable plymouth sle 12 sp3

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/umount_finish.rb, test/lib/clients/umount_finish_test.rb
=> Moved root_subvolume_read_only (boo#1077047)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_extrasources.rb, test/lib/clients/inst_extrasources_test.rb
- Related to [bsc#1076768](https://bugzilla.suse.com/show_bug.cgi?id=1076768)
- 4.0.33
=> Reimplemented finding package upgrades to require less memory

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/remote_finish_client.rb, test/remote_finish_test.rb
* 88dafa12 do not enable xvnc.socket
=> Do not enable xvnc.socket for second stage installation

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/dialogs/registration_url_dialog.rb
https://bugzilla.suse.com/show_bug.cgi?id=1083500
**Blocker** for QA
=> Pass args to parent class ctor

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/dialogs/complex_welcome.rb
* 9072b59d packaging
* d8400121 rebuild translation widget when the language has been changed
=> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_180313_translage_licenses'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/select_system_role.rb, test/select_system_role_test.rb
- https://trello.com/c/WmjvFAZP
- [bsc#1084674](https://bugzilla.suse.com/show_bug.cgi?id=1084674)
Quick testing:
```sh
rake run[inst_system_role]
```
or
```sh
DISPLAY= rake run[inst_system_role]
```
=> Enable many, many roles (with a RichText widget)

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/vnc.sh
- Supersedes #674 
- https://trello.com/c/rkYtkFT1
- [bsc#1078785](https://bugzilla.suse.com/show_bug.cgi?id=1078785)
=> Start webvnc during the installation

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/vnc.sh
- [bsc#1089623](https://bugzilla.suse.com/show_bug.cgi?id=1089623)
- https://trello.com/c/lz1iZGLQ
=> Fixed "vnc.sh: /root/.profile: No such file or directory" 

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb
Related to https://github.com/yast/yast-autoinstallation/pull/432.
=> Do not warn too soon about missing disks

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/umount_finish.rb, test/lib/clients/umount_finish_test.rb
Needed for https://trello.com/c/dqXhOfwl/379-2-sles15-p1-1091047-build-5881-openqa-test-fails-in-awaitinstall-cannot-umount-dev-vdb1
=> Fix read only subvolume

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb, test/lib/clients/inst_system_analysis_test.rb
=> Fix auto master

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/copy_files_finish.rb
goal is to have as minimal and non-intrusive change as possible.
=> Copy active devices

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_congratulate.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1095251
=> Firstboot: shutdown on failure and hide abort when congratulating

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_congratulate.rb, startup/YaST2.call
=> Merge SLE-15-GA into master

package/yast2-installation.changes, package/yast2-installation.spec, test/lib/clients/inst_system_analysis_test.rb
For https://trello.com/c/kkmPuoxR/94-3-1073633-l3-system-auto-mounts-ext4-partition-on-xen-pv-device-after-fs-resize-causes-yast-error.
=> Bsc1073633

autoyast_desktop/deploy_image.desktop, autoyast_desktop/ssh_import.desktop, package/yast2-installation.changes, package/yast2-installation.spec, src/desktop/release_notes.desktop
* Added additional searchkeys to desktop file
=> Added additional searchkeys to desktop file (#722)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/copy_files_finish.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1099104
=>  Do not rely on copy_ssh_files returned value (bsc#1099104) 

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/ssh_config.rb, test/ssh_config_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1097661
=> Do not crash in case /etc/os-release is a directory

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1101879
=> Do not print errors if plymouth is not installed

package/YaST2-Firstboot.service, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_congratulate.rb
Backport changes done in this PR https://github.com/yast/yast-installation/pull/716 as requested in https://bugzilla.suse.com/show_bug.cgi?id=1103525
=> Backport changesd done in #716 for SLE-12-SP4 (bsc#1103525)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/services.rb, test/services_test.rb
Part of https://trello.com/c/0tG0L56x/161-reorganize-yast2-service-classes
=> Update calls to Yast2::Systemd::Service

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb
For https://trello.com/c/kmmTHktz/292-sles15-p5-1092757-do-not-translate-snapshot-descriptions.
=> do not translate snapshot description (bsc#1092757)

package/yast2-installation.changes, package/yast2-installation.spec, startup/YaST2.call
Related to https://trello.com/c/puy8oO9g/353-sles15-p2-1109659-missing-fi-in-yast-installation
=> Fix syntax error

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
https://trello.com/c/PAVZthmL
- Documentation to _control.xml_:
- Documented new global parameter _enable_local_users_
- Fixed a lot of broken English (it was all over the place and sometimes really confusing)
https://github.com/yast/yast-installation-control/pull/73
https://github.com/yast/yast-yast2/pull/867
https://github.com/yast/yast-users/pull/184
=> Allow system role to default to no local user

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/transfer/file_from_url.rb, test/file_from_url_test.rb
Part of PBI: https://trello.com/c/AzEDChwZ/520-issues-from-yast-audit-systemlog-backtickslog
Requires this https://github.com/yast/yast-yast2/pull/876
=> Hardening commands execution

package/yast2-installation.changes, package/yast2-installation.spec, startup/YaST2.call
=> Respect Textmode=1 when installing over SSH with a DISPLAY (SP5)

package/yast2-installation.changes, package/yast2-installation.spec, startup/YaST2.call
- `check_network()` should not implicitly change `Y2_MODE`
- the comment in the code complaining about changing `Y2_MODE` in step 7 was right
=> ensure that installation with VNC + textmode still installs via VNC (bsc#1129073)

doc/control-file.md
Related to https://bugzilla.suse.com/show_bug.cgi?id=1121256
---
More information at https://github.com/yast/yast-country/pull/206#issue-261275232
=> Add readonly_language element documentation

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/transfer/file_from_url.rb, test/file_from_url_test.rb
This is a back port of https://github.com/yast/yast-installation/pull/797
=> cherry-pick from SLES15-SP1. Mounting CD correctly.

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/ssh_key.rb, test/ssh_key_test.rb
<sub>The same that #803, but using `git merge` instead `git rebase`</sub>
It seems that all changes made for `SLE-12-SP4` after [ Aug 3, 2018](13c9b0c0f0044af102be296ae8f2a5bfe4fb1f30) were wrongly submitted to the `SLE-12-SP5` branch. 
Merge `SLE-12-SP5` into `SLE-12-SP4`
=> Fix SLE-12-SP4

Dockerfile, Rakefile
> Adapt Rakefile and Dockerfile for SLE-12-SP5
=> Adapt Rakefile and Dockerfile for SLE-12-SP5

doc/SELF_UPDATE.md
- Small update for the self-update documentation
- https://bugzilla.suse.com/show_bug.cgi?id=1150012
=> Docu update: self-update on updated media

doc/SELF_UPDATE.md
=> [master] Docu update

src/lib/installation/dialogs/registration_url_dialog.rb, src/lib/installation/widgets/system_roles_radio_buttons.rb
- https://trello.com/c/mg7PFhw5
=> Added missing textdomains

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/ssh_config.rb, test/fixtures/root1/etc/os-release, test/ssh_config_test.rb
https://trello.com/c/oGDFwrPY/1171-2-tw-p2-1139518-tw20190623-internal-error-undefined-method-gsub-for-nilclass
=> Fix nil crash

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_system_analysis.rb
- https://jira.suse.com/browse/SLE-7101
- https://trello.com/c/URPtTjGS/1365-5-system-upgrade-using-the-offline-media
- Skip the repository initialization at upgrade also for the offline medium
- 4.2.20
=> Implement upgrade for Full medium (jsc#SLE-7101)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_finish.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1122493
=> Use linuxrc option "reboot_timeout" to configure the timeout before reboot (bsc#1122493)

package/yast2-installation.changes, package/yast2-installation.spec, test/lib/clients/inst_system_analysis_test.rb
Adapt to https://github.com/yast/yast-storage-ng/pull/1022. Further information can be found there.
=> use udevadm in /usr/bin instead of /sbin

doc/SELF_UPDATE.md, doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/update_repositories_finder.rb
Using tag $os_release_version in the control.xml file which will be replaced by the entry VERSION in /etc/os-release.
(improvement for fate#325834)
=> Master fate 325834

doc/yupdate.md
- The `yupdate` script has been finally released in the TW
- https://download.opensuse.org/tumbleweed/iso/Changes.20200314.txt
=> yupdate docu update

package/yast2-installation.changes, package/yast2-installation.spec
trello: https://trello.com/c/X6NTif5Z/1714-2-isopensuse-jira-cards
jira: https://jira.suse.com/browse/SLE-11851
=> Do not differ on opensuse

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
Fixes [bsc#1167248](https://bugzilla.suse.com/show_bug.cgi?id=1167248)
=> [bsc#1167248] Restore scroll when needed

doc/yupdate.md
- Unfortunately `yupdate` cannot fix the AutoYaST 2nd stage, let's document this.
=> Added AY 2nd stage note in the yupdate documentation

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/language.sh
=> Merge SLE-12-SP4 into SLE-12-SP5

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/language.sh
A sync merge. It mainly merges #852 although there are other PR listed.
=> Merge SLE-15-GA in SLE-15-SP1

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/language.sh
It merges #853 (original fix is in #850 )
=> Merge SLE-15-SP1 into 'master'

doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1171423
- https://trello.com/c/BqWDHmp1
Remove obsolete `proposal_settings_editable` setting from control files.
=> remove obsolete proposal_settings_editable

.travis.yml, package/yast2-installation.changes, package/yast2-installation.spec, src/autoyast-rnc/deploy_image.rnc, src/autoyast-rnc/ssh_import.rnc
trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886
=> Schema change

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/ssh_import_auto.rb, test/ssh_import_auto_test.rb
trello: https://trello.com/c/1RXM7d8u/1851-8-reduce-profile-i-do-not-export-not-relevant-information
=> Profile reduce

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/deploy_image_auto.rb, test/lib/clients/deploy_image_auto_test.rb, test/test_helper.rb
trello: https://trello.com/c/4ecKNfaX/1920-5-cloned-autoyast-profile-always-contains-unwanted-sections
=> Deploy image reduce

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/copy_files_finish.rb, test/copy_files_finish_test.rb
Port of PR https://github.com/yast/yast-installation/pull/867.
=> Bsc1172853

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_update_installer.rb, src/lib/installation/minimal_installation.rb, src/lib/installation/update_repositories_finder.rb, src/modules/InstFunctions.rb, test/inst_functions_test.rb, test/inst_update_installer_test.rb, test/lib/update_repositories_finder_test.rb
trello: https://trello.com/c/kCfh7Ylo/1941-5-drop-references-to-profilecurrent
=> remove access to autoyast profile unless it is necessary

package/yast2-installation.changes, package/yast2-installation.spec, src/modules/ImageInstallation.rb, test/image_installation_test.rb
trello: https://trello.com/c/qlBmJwiq/1934-5-handle-new-exceptions-when-serializing-deserializing-xml
=> Xml exceptions

control/test.xml, package/yast2-installation.changes, package/yast2-installation.spec, src/clients/deploy_image_auto.rb, src/lib/installation/clients/deploy_image_auto.rb, test/lib/clients/deploy_image_auto_test.rb
Creating Images will not be available anymore in AY. It is an undocumented feature which has so many bugs.
We have never gotten any bug report about it. ---> we drop it.
=> AY: cleanup image creation/deployment

package/yast2-installation.spec
=> needs yast2-bootloader to build

doc/SELF_UPDATE.md
A documentation update related to https://github.com/yast/yast-installation/pull/885
=> Describe .packages.self_update in the SELF_UPDATE.md documentation

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_finish.rb
Replaces #888. Hopefully, it should fix [bsc#1177522](https://bugzilla.suse.com/show_bug.cgi?id=1177522).
=> bsc#1177522

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_finish.rb
=> bsc#1177522 master

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_install_inf.rb, test/inst_install_inf_test.rb
=> Merge SLE-15-SP2

doc/installer_extension.md, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_update_installer.rb
trello: https://trello.com/c/Ok8Jl7S4/2158-3-superwanted-theme-changes
Goal is to unify addon versus add-on. Correct one is add-on, so lets change it in all user visible places.
=> Unify addon

doc/control-file.md
The documents about the storage proposal were messy because they were left in a state where they documented the transformation process from yast-storage into yast-storage-ng instead of focusing on the status quo.
1) The reference documentation of the control file (in this repo) was still describing the old yast-storage format
2) The more detailed documentation at yast2-storage-ng was written as some kind of list of differences with the obsolete old format, instead of simply describing the present.
The solution comes in two pull requests: this one and https://github.com/yast/yast-storage-ng/pull/1205
This one updates the information in the control file documentation, ditching the yast-storage content and replacing it with reference information that was originally found at the …
=> Update documentation to reflect yast-storage-ng (bsc#1175098)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb, test/snapshots_finish_test.rb
Merge #901 into the `SLE-15-SP2` branch.
=> Merge SLE-15-SP1

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/security_finish.rb, src/lib/installation/clients/security_proposal.rb, src/lib/installation/security_settings.rb, src/lib/installation/widgets/polkit_default_priv.rb, test/lib/clients/security_finish_test.rb, test/lib/clients/security_proposal_test.rb
fix of https://github.com/yast/yast-installation/pull/906#issuecomment-786033802
screenshot of summary with selinux:
=> Security proposal

package/yast2-installation.changes, package/yast2-installation.spec, src/clients/security_finish.rb, src/lib/installation/clients/security_proposal.rb, test/lib/clients/security_proposal_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1182821
related: https://github.com/yast/yast-security/pull/81
=> Fix sec finish

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/security_finish.rb, test/lib/clients/security_finish_test.rb
one part of fix for https://bugzilla.suse.com/show_bug.cgi?id=1182894
=> Security upgrade

package/yast2-installation.changes, package/yast2-installation.spec, startup/common/network.sh
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1183188
backport of https://github.com/yast/yast-installation/commit/7ef133a43f46461fbf749b7c23dca8b294c84b87#diff-ffb0c90720c792cb72a110ac1d0da94291df5a060320886cd29964743d60158e
=> Backport bashism

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb, test/snapshots_finish_test.rb
Backports the fix for [bsc#1180142](bugzilla.suse.com/show_bug.cgi?id=1180142). See https://github.com/yast/yast-installation/pull/901.
=> Backports fix for bsc#1180142

package/yast2-installation.changes, package/yast2-installation.spec, src/include/installation/misc.rb, src/lib/installation/clients/copy_files_finish.rb, src/lib/installation/clients/inst_finish.rb, test/copy_files_finish_test.rb
Backport linuxrc option reboot_timeout to 15 SP1
https://progress.opensuse.org/issues/89716
See https://github.com/yast/yast-yast2/pull/1159 && https://github.com/openSUSE/installation-images/pull/505
=> Use linuxrc option reboot_timeout to configure the timeout before reboot

doc/control-file.md
Document the `network` section
- https://trello.com/c/Jao9dDKQ/2477-5-make-forwarding-configurable-for-installer
- https://bugzilla.suse.com/show_bug.cgi?id=1186280
=> Document network section

.rubocop.yml, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/upgrade_repo_manager.rb, test/lib/upgrade_repo_manager_test.rb
- Merging https://github.com/yast/yast-installation/pull/963 to `master`
=> [master] Improve evaluating the old repositories (bsc#1185822)Old addons master

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/proxy_finish.rb, startup/common/misc.sh, test/lib/clients/proxy_finish_test.rb, test/test_helper.rb
It merges #965 and needs yast/yast-proxy#45
=> Merge SLE-15-SP3 into 'master'

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_disks_activate.rb, test/inst_disks_activate_test.rb
Port  https://github.com/yast/yast-installation/pull/972 to SLE-15-SP3.
=> Activate devices (SLE-15-SP3)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_disks_activate.rb, test/inst_disks_activate_test.rb
Port  https://github.com/yast/yast-installation/pull/972 to SLE-15-SP4 (master).
=> Activate devices (SLE-15-SP4)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_download_release_notes.rb, test/lib/clients/inst_download_release_notes_test.rb
=> [master] Display release notes during upgrade (bsc#1186044)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
Forward porting #980 by merging SP1 into SP2
=> Fix displaying a custom proposal set in AY (SP2)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
Forward porting #980 by merging SP2 into SP3
=> Fix displaying a custom proposal set in AY (SP3)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/proposal_runner.rb
Forward porting #980 by merging SP3 into master
=> Fix displaying a custom proposal set in AY (master)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/dialogs/complex_welcome.rb, test/lib/dialogs/complex_welcome_test.rb
Fix the title corresponding to the #999 changes.
=> Fix complex welcome title

doc/control-file.md
See https://github.com/yast/yast-installation-control/pull/115.
=> Document mount_options attribute

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb, test/snapshots_finish_test.rb
Merge #1003 into `SLE-12-SP4`.
=> Merge bsc#1180142 fix into SLE-12-SP4

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/snapshots_finish.rb, test/snapshots_finish_test.rb
Merge #1003 and #1004 into `SLE-12-SP5`.
=> Merge bsc#1180142 fix into SLE-12-SP5

package/yast2-installation.changes, package/yast2-installation.spec
It needs https://github.com/yast/yast-yast2/pull/1227
=> Update yast2 dependency

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/security_proposal.rb, src/lib/installation/dialogs/security.rb, src/lib/installation/widgets/lsm.rb, src/lib/installation/widgets/selinux_mode.rb
Just some changes suggested during the review of https://trello.com/c/0KpnKW6N/2754-8-feature-shouldhave-unify-selinux-and-apparmor-solution-in-the-installation-summary
=> LSM proposal configuration changes

doc/control-file.md
Documentation for https://github.com/yast/yast-bootloader/pull/665
=> document boot timeout option (jsc#SLE-22667)

package/yast2-installation.changes
Fix feature reference (see #1020).
=> Fix feature reference in the changes file

package/yast2-installation.changes, package/yast2-installation.spec
This is a follow-up for https://github.com/yast/yast-installation/pull/1026
It includes only the version bump (and corresponding changelog entry) needed to trigger the submission to TW and 15.4.
=> Version and changelog for VNC fix

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
See https://github.com/yast/yast-installation/pull/1030.
=> Avoid login (port to SP4)

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
=> Run YaST2-Second-Stage after purge-kernels service (SLE-15-SP4 / TW)

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec, startup/Second-Stage/S09-cleanup, startup/YaST2.call, startup/common/misc.sh
=> Add Before=xvnc.socket dependency to Firstboot and Second Stage services (bsc#1197265) in SLE-15-SP4 / TW

README.md
- https://bugzilla.suse.com/show_bug.cgi?id=1181606
- https://trello.com/c/zpCgMia9
=> Explain the status of Live Installation (bsc#1181606)

package/YaST2-Firstboot.service, package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec, startup/First-Stage/F08-logging, startup/Second-Stage/S09-cleanup, startup/YaST2.call, startup/common/misc.sh
It merges #1041 into SLE-15-SP4
=> Revert "AY: Do not stop xvnc.socket but rely on systemd" in SLE-15-SP4

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
It merges #1044 which contains the description and explanation
=> Added Before=serial-getty@sclp_line0.service to YaST2-Second-Stage.service (SLE-15-SP4)

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
=> Added Before=serial-getty@sclp_line0.service to YaST2-Second-Stage.service (master)

package/yast2-installation.changes, package/yast2-installation.spec
It merges #1048 into SLE-15-SP4
=> Do not restart services when the package is updated (SLE-15-SP4)

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
It merges #1053 into SLE-15-SP4
=> Before user sessions (SLE-15-SP4)

package/YaST2-Second-Stage.service, package/yast2-installation.changes, package/yast2-installation.spec
It merges https://github.com/yast/yast-installation/pull/1053 into 'master'
=> Before user sessions (master)

src/lib/installation/clients/pre_umount_finish.rb
Fix return of the poolsize for #1064
=> Fix return poolsize

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/pre_umount_finish.rb, src/lib/installation/clients/security_finish.rb, src/lib/installation/proposal_store.rb, test/lib/clients/pre_umount_finish_test.rb, test/lib/clients/security_finish_test.rb
Merge SLE-15-SP4 into `master`
=> Merge SLE-15-SP4 into master

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/security_proposal.rb
Just merging #1082 to `master`.
=> [master] Removed unnecessary executable flag (bsc#1209094)

bin/yupdate, package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_upgrade_urls.rb, startup/YaST2.call
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
apply all fixes from master to SP6.
=> Backport sp6

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/inst_upgrade_urls.rb, src/lib/installation/upgrade_repo_manager.rb, test/lib/clients/inst_upgrade_urls_test.rb, test/lib/upgrade_repo_manager_test.rb
- Just merging fix #1098 to the SP6 branch
=> [SLE15-SP6] Refresh repositories with changed URL and reload them again

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/transfer/file_from_url.rb, test/file_from_url_test.rb
Merge fix for [bsc#1217637](https://bugzilla.suse.com/show_bug.cgi?id=1217637) into `SLE-15-SP6` (see #1101).
=> bsc#1217637: retrieve an AutoYaST profile on a NFS+IPv6 setup (SLE-15-SP6)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/upgrade_repo_manager.rb, test/lib/upgrade_repo_manager_test.rb
Just porting #1106 to master...
=> [master] Restore the selected products (bsc#1218391) 

doc/SELF_UPDATE.md, doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
- Related to https://jira.suse.com/browse/PED-4839
- The URL in the documentation should be updated as well
- Updated URL
=> Updated self-update URL in the documentation (jsc#PED-4839)

doc/SELF_UPDATE.md, doc/control-file.md, package/yast2-installation.changes, package/yast2-installation.spec
=> [master] Updated self-update URL in the documentation (jsc#PED-4839)

package/yast2-installation.changes, package/yast2-installation.spec, src/include/installation/inst_inc_all.rb
=> Fix call for connecting all discovered NVMe-over-Fabrics subsystems (bsc#1222246) (master)

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/dialogs/security.rb, src/lib/transfer/file_from_url.rb
This is in conjunction to 
https://github.com/yast/yast-bootloader/pull/700
=> Set cpu_mitigations for different bootloaders Grub/systemd-boot

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/clients/copy_files_finish.rb, test/copy_files_finish_test.rb
=> Merge brokenmodules

package/yast2-installation.changes, package/yast2-installation.spec, src/lib/installation/instsys_packages.rb, test/instsys_packages_test.rb
- Just merging #1130 to SLE15-SP7
=> [SLE15-SP7] Fixed comparing versions in the self-update version check
