- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.Second-Stage
AutoYaST: If the system starts in multi-user mode plymouth will
be quit while installation in order to ensure that installation
will be finished on console 1 and the login prompt will be
shown.
> Plymouth bug 903682

- package/yast2-installation.changes
- package/yast2-installation.spec
- The approach with %service_add_post works only for new installations but doesn't work for upgrades
- bsc#924278
> Always enable startup scripts for Second Stage and Firstboot

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/common/vnc.sh
...to fix broken layout in VNC installations (defaults to 75 dpi).
The installation stylesheet uses units like 'em' or 'pt' [*] which
depend on the display resolution (dpi).
- 3.1.142
[*] see http://www.w3.org/Style/Examples/007/units.en.html
> Set Xvnc server resolution to 96 dpi (bsc#919456)

- doc/proposal_api.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
- src/lib/installation/proposal_store.rb
- test/proposal_store_test.rb
In some cases, proposals depend on each other. For instance, kdump sets required packages for software proposal, but software proposal influences space available on disk and kdump needs to evaluate this space whether dump fits there (FATE#317488). There have been several other cases in the past. That's why I've created a generic handling using triggers.
Each proposal client can define so called `trigger` with keys `expect` and `value`. All these triggers are evaluated at the end of the proposal and if output of the `expect` does not match `value`, proposal will be called again. All such proposals are called after all triggers are evaluated and then triggers are evaluated again. There is a counter that breaks from an infinite loop if needed.
> Implemented "triggers" for calling installation proposals again when needed

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
- src/lib/installation/clients/inst_system_analysis.rb
This is covered by openQA (that's how the bugreport appeared)
> avoid suplicating release notes for products (bsc#935599)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/inst_system_analysis_test.rb
This PR fixes [bsc#940648](https://bugzilla.suse.com/show_bug.cgi?id=940648). BTW, unit tests were added.
> Fix release notes loading when network is not working

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- startup/common/misc.sh
- startup/common/vnc.sh
It was introduced to avoid a very remote possibility of race condition. Now it's double checked in the startup script.
Tested manually with a successful vnc+autoyast installation and also simulating the race condition.
@imobach is running it through the entire autoyast test suite.
> Remove systemd dependency on xinetd

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
[bsc#935965](https://bugzilla.suse.com/show_bug.cgi?id=935965)
https://trello.com/c/q47excv8
A follow-up to #320.
It turns out that the failure the customer reported was a real problem with our earlier fix, caused by an even more uncommon setup.
> Don't let getty kill YaST on further serial consoles (bsc#935965)

- .travis.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/Makefile.am
- src/lib/transfer/file_from_url.rb
- test/Makefile.am
- test/file_from_url_test.rb
Moves `Transfer::FileFromUrl` from yast-update to yast-installation, as it's needed by #347. More information in https://github.com/yast/yast-update/pull/53 which moved it from AutoYaST2 to yast2-update.
> Move file from url

- package/yast2-installation.spec
rpm macros get expanded in comments as well.
This one leads to weird errors during installation,
like "Failed to execute operation: No such file or directory".
> Fix macro expansion in %post comment

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
A missing piece to complete https://trello.com/c/0mOtUy45/467-8-sle-12-sp2-p4-m-feature-317481-add-system-role-capabilities-to-installer , continuing #340.
> Changing the system role may undo adjustments you may have done.

- src/lib/installation/clients/inst_update_installer.rb
Part of https://trello.com/c/LoAaDF97/468-8-sle-12-sp2-p1a-m-feature-319716-automatic-update-of-yast-at-beginning-of-the-installation
As it's shown as another step in the system analysis, I guess we should remove this popup (it's a leftover from the previous UI).
> Remove an extra popup during installer update

- package/yast2-installation.spec
This is a fix up for the previous PR #357, the `proc_modules.scr` file has been moved to yast2 but the spec file was not updated.
Unfortunately not found by Travis as we do not build the package there, found by Jenkins later...
> Fixed spec file

- src/lib/installation/clients/inst_disks_activate.rb
- test/inst_disks_activate_test.rb
I had unified the distribution of `[Network Configuration]` button.
**Previous**
**Now**
> Unifying network button position in activation of disks client. (FATE#319716)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
- test/test_helper.rb
Extends #352, #356 also to AutoYaST mode.
See [FATE#319716](https://fate.suse.com/319716).
The AY profile schema is updated in https://github.com/yast/yast-autoinstallation/pull/206.
> Support for self update in AY mode

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/clients/inst_disks_activate.rb
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_complex_welcome_test.rb
- test/inst_disks_activate_test.rb
- test/inst_update_installer_test.rb
During the tests i realized that the license agreement was not remembered so i also fix it.
> Skipped disk activation step in case of installer updated (bsc#974409)

- package/yast2-installation.spec
In the previous PR #367, the required version were not added:
yast/yast-yast2#463
yast/yast-packager#155
> Modified required versions of yast-packager and yast-yast2 (bsc#974409)

- package/yast2-installation.spec
- src/lib/installation/clients/installation.rb
Optionally start the Ruby debugger at the beginning of installation. The debugger is started using `Y2DEBUGGER` boot option.
*Note: the debugger invocation is implemented here: https://github.com/yast/yast-ruby-bindings/pull/167*
The supported modes are:
- `Y2DEBUGGER=1` - enable the debugger, in Qt UI the debugger frontend is started automatically
- `Y2DEBUGGER=remote` - make the debugger remotely accessible, connect using `byebug -R <host>:3344` command (in the other cases the debugger can be accessed *only localy*)
- `Y2DEBUGGER=manual` - like `1`, but does not start the the debugger frontend automatically
(Click a screenshot to see the full size image.)
- GUI with `Y2DEBUGGER=1` - the debugger console is opened automatically
- Text mode with `Y2DEBUGGER=1` - the debugger console must …
> Ruby debugger integration (FATE#318421)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_pre_install.rb
- src/lib/installation/clients/ssh_import_proposal.rb
- src/lib/installation/dialogs/ssh_import.rb
This pull request is just for some minor changes based on [blog entry](https://lizards.opensuse.org/2016/05/18/highlights-of-yast-development-sprint-19/) feedback. The functionality was added and is explained in #374.
https://trello.com/c/EQzfj9Kf
In case that there is not a previous installation the proposal will be disable:
In other case:
And the new dialog suggested by @kwwii:
> SSH import proposal summary interface improvements (Fate#319624)

- package/yast2-installation.changes
- src/lib/installation/select_system_role.rb
Testing #382 i realized that system role dialog was also not centered.
So, after merge this PR it will look like..
> System Role: centered dialog for ncurses.

- src/lib/installation/clients/ssh_import_auto.rb
- src/lib/installation/ssh_importer.rb
- test/Makefile.am
- test/ssh_import_auto_test.rb
This PR is based on #380:
* Add unit test for `SSHImportAutoClient`.
* Move code from `SshImporter` to `SSHImportAutoClient`. IMHO, the main responsible for handling the import/write/etc. at a "top-level" should be the client itself. SshImporter class shouldn't now anything about AutoYaST, although it's the class that does the final job.
On the other hand, I'm not sure if `SSHImportAutoClient` should be here or in `yast-autoinstallation`.
@schubi2 Of course, I could be wrong :). In that case, you can use at least the unit tests :) Feel free to cherry pick them.
> Review 319624 AutoYaST

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/installation.rb
... to use the same implementation at run time.
- 3.1.190
The related ruby-bindings PR is here: https://github.com/yast/yast-ruby-bindings/pull/168
> Move the debugger invocation to ruby-bindings (FATE#318421)

- autoyast_desktop/ssh_import.desktop
- src/lib/installation/clients/ssh_import_auto.rb
- src/lib/installation/clients/ssh_import_proposal.rb
- src/lib/installation/ssh_importer_presenter.rb
- test/ssh_import_auto_test.rb
- test/ssh_importer_presenter_test.rb
Updates from code review for #380.
As we need `SshImporterProposal` and `SshImporterAutoClient` to show the same `summary`, instead of moving this logic to `SshImporter#summary`, I preferred to add a presenter. I don't like the idea of `SshImporter` knowing about i18n or HTML.
> ssh import: updates from code review

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/update_repository.rb
- test/inst_update_installer_test.rb
Fix architecture detection. It fixes [bsc#984656](https://bugzilla.suse.com/show_bug.cgi?id=984656).
> Fix architecture detection

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/update_repository.rb
- src/lib/installation/updates_manager.rb
- test/inst_update_installer_test.rb
- test/updates_manager_test.rb
Fixes [bsc#985113](https://bugzilla.suse.com/show_bug.cgi?id=985113).
> Avoid restarting YaST when self-update repo is empty

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
The current error message is a bit scary for the customers, we need to tell them that the installer updates are optional and it is OK to continue without them.
See [bug #986091](https://bugzilla.suse.com/show_bug.cgi?id=986091) for more details.
- 3.1.197
> More information in the self update error popup (bsc#986091)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/cio_ignore.rb
- src/lib/installation/clients/inst_disks_activate.rb
- src/lib/installation/proposal_runner.rb
- src/lib/installation/ssh_importer_presenter.rb
- startup/YaST2.call
This is a fix up for commit 65a6b6f0.
The `oom_score_adj` file has a different range than the original `oom_adj`, value `-1000` is the equivalent of the original `-17`.
See the [kernel proc documentation](https://www.kernel.org/doc/Documentation/filesystems/proc.txt), section 3.1.
*Note: the second commit is actually just an update for the Rubocop config (https://github.com/yast/yast-devtools/pull/107).*
- 3.1.200
> Fixed OOM killer setup

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
It should fix [bsc#988949](https://bugzilla.suse.com/show_bug.cgi?id=988949). When running AutoYaST, if the self-update repo cannot be probed, it just show a error and don't halt the installation (unless the profile is configured to stop on errors).
> Don't halt AutoYaST installation on self-update problem

- src/lib/installation/clients/ssh_import_auto.rb
found by y2tool y2makepot
IMHO the messages occur in [fairly rare cases](https://github.com/search?utf8=%E2%9C%93&q=translators+sense+path%3Asrc%2Flib%2Finstallation%2Fclients&type=Code&ref=advsearch&l=&l=) so I am not making a bug for this.
> Declare textdomain to fix untranslated texts

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- Code that handles license checkbox moved to prevent from warnings"No widget ID..."
- The License Text widget is now initialized ASAP
- Changing the License widget when its text is actually known
- The new code has been tested and optimized especially for the user (UI, UX), while keeping the actual openQA-related bug in mind as well (bsc#980374)
- The client has a good test case which does not need to be extended
- @license_accepted variable has been replaced by InstData.product_license_accepted because of conflicts in data duplication
> UI and UX Optimizations in Welcome Screen

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/update_repository.rb
- src/lib/installation/updates_manager.rb
- test/inst_update_installer_test.rb
Improved version of #400 to support multiple URLs coming from SCC/SMT.
It depends on https://github.com/yast/yast-registration/pull/263 (merged).
>  Get self-update URL from SMT through SUSEconnect (with multiple URLs support)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
Fixes a problem introduced [here](https://github.com/yast/yast-installation/pull/401/commits/e27cc92d5d5f45d48808b4e1fcb54499778e6c50#diff-8aa15970732082407af8655c128f0913R168).
The registration URL used during self-update is stored to be the default option in the registration screen. However, due to the change mentioned above, it was stored accidentally converted from `nil` to `""` if SCC was used.
This patch just skip writing the URL if not needed.
> Don't save custom_url when SCC is used during self-update

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_prepareprogress.rb
- src/lib/installation/snapshots_finish.rb
To make travis work again we need to be able to build and install some basic packages without bringing yast2-storage in. We don't need all the code to actually work, just the one executed in our installation (already fixed/commented in https://github.com/yast/yast-installation/pull/403).
This pull request removes the dependency from the spec file and cleanups some bits of code. Hopefully enough to get travis working again.
> Remove old libstorage dependency

- .travis.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
To check it works, just run the installer and search for these lines in the logs after the system analysis step:
```
probed devicegraph begin
[...here is the information about your hardware as it's loaded in memory...]
probed devicegraph end
```
Tested in qemu-kvm with IDE & SCSI. Should work in real hardware and VirtualBox as well.
This goes together with https://github.com/yast/yast-storage-ng/pull/87
> Use y2storage for hardware probing

- package/yast2-installation.changes
- package/yast2-installation.spec
- test/inst_complex_welcome_test.rb
- The test actually tests behavior of the ProductLicense (a bit) instead of testing the client only
- That's something I can't and will not fix now
- See also https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:J/yast2-installation/standard/x86_64
> Fixed test-case after implementing lazy loading in ProductLicense

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/dialogs/ssh_import.rb
By some reason the Label of the CheckBoxFrame is being cut. Now width is forced, but could be nice if some UI expert reviewed it as i'm not sure if could be some problem with long texts **(translations)**.
> SSH Importer: Width fix to avoid cut of CheckBoxFrame Label

- src/lib/installation/proposal_runner.rb
- src/lib/installation/proposal_store.rb
it do not deserve own changelog entry as it is just more debugging, so fine if it is send later to BS
> add more logging to debug (bnc#994127)

- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
- test/test_helper.rb
I tried to do as minimal as possible not handling all the stuff that currently autoinit is handling, just enough to read the self_update_url.
So from here https://github.com/yast/yast-autoinstallation/blob/master/src/clients/inst_autoinit.rb#L196 to the end is not handled.
> [WIP] Fetch profile from update installer

- doc/SELF_UPDATE.md
Just some minor improvements in the self-update documentation:
* Unify `self-update` and `self update`.
* Add a link to the `/general/signature-handling` section when using AutoYaST.
> Minor improvements in SELF_UPDATE.md documentation

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
When the registration server fails or returns empty URL then the fallback URL from `control.xml` was silently used. This might be a bit misleading because users might think the SMT server is still used after confirming the error popup. It's not clear which URL is used in the end.
This fixes [bug#996179](https://bugzilla.suse.com/show_bug.cgi?id=996179).
*Click the screenshots to display them in full size.*
Note the default `https://updates.suse.com/` URL in the progress after confirming the error. If you do not look carefully you might still think the originally selected SMT is used, that's not true.
There is a popup warning displayed when the fallback URL is used.
*(The SSL import dialog is not displayed because this was tested it in the same installation instance, the certificate has …
> Display a warning when using the fallback URL for self update (bsc#996179)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
Set theme for ncurses in order to honor the `Y2COLORMODE` setting. I've decided to add a `set_inst_ncurses_env` in make it symmetric to the Qt scenario.
Depends on https://github.com/yast/yast-yast2/pull/501 and it's related to https://github.com/libyui/libyui-qt/pull/60 and https://github.com/libyui/libyui-qt/pull/61.
> Set theme for ncurses

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
Merge the Octopus branch into CASP to clean up the mess. Removed conflict in the version change.
(*Note: Ignore the Jenkins failure, the SP2 project is not yet available in the public OBS.*)
> Merge SLE-12-SP2-Octopus into SLE-12-SP2-CASP

- README.md
- doc/installation_clients.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
- src/lib/installation/proposal_store.rb
- test/proposal_store_test.rb
This implements the support for the read-only proposal modules, [FATE#321739](https://fate.suse.com/321739).
The code has been tested with software and firewall proposal modules set to read-only mode:
```xml
<proposal_module>
<name>software</name>
<presentation_order>35</presentation_order>
<read_only config:type="boolean">true</read_only>
</proposal_module>
<proposal_module>
<name>firewall_stage1</name>
<presentation_order>50</presentation_order>
<read_only config:type="boolean">true</read_only>
</proposal_module>
```
The software and firewall proposal modules then do not display the links in the section header (note the different color), the modules are not reachable:
However the links returned in the proposal summary are still displayed. But clicking them results in a warning popup and …
> Support for read-only proposal modules (FATE#321739)

- doc/control-file.md
Adding documentation about the readonly_timezone feature. I think that releasing a new `yast2-installation` package is not needed.
> Add readonly_timezone element documentation

- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/umount_finish.rb
https://trello.com/c/sLkMAwRU/479-3-casp-321755-microos-switch-root-subvolume-to-read-only-s
This PR is the code and XML documentation part.
PR for the XML schema and the CASP control.xml (skelcd-CASP) will follow.
Please notice the PBI called for a simple solution. This approach will fail silently if the configuration parameter is set in control.xml, but the root filesystem type is something other than Btrfs.
> Set root subvolume read-only for CASP if configured (Fate#321755)

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
* 681a57c init tty1 in second stage of AY installation
* 5bf0acb init tty1 after installation has been finished (bnc#1018037)
* 4bbdc51 Merge pull request #477 from yast/readonly-timezone-doc-sp2
* 1772f68 Add readonly_timezone element documentation
* 4b34345 Bsc 1013976 (#471)
> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_170109_init_tty1'

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
- src/lib/installation/proposal_store.rb
- test/proposal_runner_test.rb
- test/proposal_store_test.rb
https://trello.com/c/sEVjWKcJ/780-3-casp-read-only-software-selection
Proposals in control file currently have format:
```
<proposal_module>
<name>software</name>
<read_only config:type="boolean">true</read_only>
</proposal_module>
```
this PR changes this to
```
<proposal_module>
<name>software</name>
<read_only>soft</read_only>
</proposal_module>
```
> Enable RO proposal in case of error

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_update_installer_test.rb
Using the following snippet allows to disable the self-update using an AutoYaST profile:
```xml
<general>
<self_update config:type="boolean">false</self_update>
</general>
```
I'm also removing the step `Fetching AutoYaST Profile`. Why? Because I think that we should show the same UI if you disable the self-update via Linuxrc (no progress is shown) or via a profile. It can be confusing to see the `Updating Installer` screen (although for 1 sec) if you explicitly has disabled it.
> Disable self update via AutoYaST profile

- test/inst_casp_overview_test.rb
It was failing because stubbed in #507
> Mock Yast::Language.language call for #507

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
* 6b9a6d2 merged from SP2
* 6d83b44 release download: break downloading if the host/proxy cannot be resolved (#511)
* 5bf0acb init tty1 after installation has been finished (bnc#1018037)
* 4bbdc51 Merge pull request #477 from yast/readonly-timezone-doc-sp2
* 1772f68 Add readonly_timezone element documentation
* 4b34345 Bsc 1013976 (#471)
> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_170202_error_download_release_notes'

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_casp_overview.rb
- test/inst_casp_overview_test.rb
...when it is present
- Reuses the existing code, no change needed
- Unit tests included
- Tested manually (see the screenshots below)
> CaaSP: Display the Beta product warning at start (bsc#1016887)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/system_roles/handlers.rb
- test/roles_finish_test.rb
- test/system_role_handlers_test.rb
This is an easy fix allowing dashes url although the best option is to use a custom salt lense. It is valid because we don't expect to update the file but just create it.
> Fix dashed url (bsc#1024965)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/update_repositories_finder.rb
- src/lib/installation/update_repository.rb
- test/inst_update_installer_test.rb
- test/lib/update_repositories_finder_test.rb
- test/support/fake_registration.rb
- test/update_repository_test.rb
As you may know, YaST includes a [nice feature](https://fate.suse.com/319716) which allows the installer to update itself in order to solve bugs in the installation media. This mechanism has been included in SUSE Linux Enterprise 12 SP2, although it's not enabled by default (you need to pass an extra option `selfupdate=1` to make it work).
So after getting some feedback, we're working toward fixing some usability problems. The first of them is that, in some situations, the self-update mechanism is too intrusive.
Consider the following scenario: you're installing a system behind a firewall which prevents the machine to connect to the outside network. As the SUSE Customer Center will be unreachable, YaST complains about not being able to get the list of repositories for the self-update. …
> Self-update refactoring

- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- src/lib/installation/system_role.rb
- test/select_system_role_test.rb
- test/system_role_test.rb
This PR adds support to allow add-ons to add new roles and requires https://github.com/yast/yast-yast2/pull/542.
Apart from that, I adapted the `SelectSystemRole` dialog to use the `SystemRole` class written by @teclator.
> Add system roles through addons

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
This PR improves how role buttons are distributed in textmode. The point is that adding a role didn't fit in the 80x25 mode. Now separation is adjusted and, if roles don't fit even without separation, the description and the introductory text will be omitted.
If roles don't fit even without the description, the [introductory text will be also omitted](https://github.com/yast/yast-installation/pull/537/files#diff-b9cac9df8ec348a3c81180e449f766e8R234).
> Redistribute roles buttons space

- doc/installer_extension.md
*Note: review the [rendered document](https://github.com/yast/yast-installation/blob/installation_xml_doc/doc/installer_extension.md), it looks much better than a plain MD file...*
- The installer allows adding new steps
- Or adding new roles
The YaST installer already allows extending the installation work flow by add-on extensions. However, this was only supported for the SUSE tag repositories (ISO installation media). That means that online repositories, which normally use RPM-MD data format, could not be used with feature.
This sprint we extended the support also for the other repository formats (basically any repository format supported by libzypp). The original limitation was caused by the fact that the other repository types do not support other files except the RPM packages.
To …
> The installer extension documentation

- package/yast2-installation.spec
The yast2-slp dependency was introduced in dde4be57. As the code have been moved to CaaSP, this dependency is not needed anymore.
> Remove yast-slp dependency

- package/yast2-installation.spec
- src/clients/inst_install_inf.rb
- src/lib/installation/clients/inst_install_inf.rb
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/dialogs/registration_url_dialog.rb
- src/lib/installation/dialogs/url_dialog.rb
- src/lib/installation/update_repositories_finder.rb
- test/inst_install_inf_test.rb
- test/lib/update_repositories_finder_test.rb
- test/support/fake_registration.rb
The idea is to reuse the network 'inst_install_inf' not just writing the hostname and proxy configuration but also checking wrong urls provided in the command line.
The new `::Installation::URLDialog` should be moved to yast-yast2 using the `UI` namespace instead of `Installation`
The current approach allows the user to fix the url, or nullify it in case of not fixed (abort).
In case of `AutoYast`, after discussed with @imobachgs seems that we should continue just reporting it to not block the installation..
In the registration step it will handle it just as a connection error, reporting it so no change is needed there.
> Early check of wrong urls allowing to fix them (bsc#1035908)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/widgets/online_repos.rb
- Use `Configure Online Repositories` (without dash)
- See https://bugzilla.suse.com/show_bug.cgi?id=1039988
- 3.2.40
> Fixed push button label (bsc#1039988)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/widgets/hiding_place.rb
In this PR yast/yast-yast2#573, the requirement of "cwm/widget" was moved to a method probably because of some recursive dependency conflict. So I have replaced the import by a requirement.
> Add 'cwm/widget' requirement because of changes made for (boo#1039901)

- package/yast2-installation.changes
- src/lib/installation/widgets/system_roles_radio_buttons.rb
- test/lib/widgets/system_roles_radio_buttons_test.rb
We have fixed two different issues,
First of all it fixes the lost of desktop selection when the "Online repositories" is clicked (bsc#1033594)
And secondly we now requires at least the selection of one desktop to continue with the installation fixing (bsc#1040884)
Trello card: https://trello.com/c/40ZZxO2D/
A new card has been created to take care or handle by default the events not only of the main widget but also the buttons below it https://trello.com/c/0gsQI7Gf
> Don't forget desktop selection (bsc#1033594)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/widgets/system_roles_radio_buttons.rb
- test/lib/widgets/system_roles_radio_buttons_test.rb
* 68b9065 Initialize pattern selection in the custom role workflow with patterns defined in the control file.
This should be submitted together with
https://github.com/yast/skelcd-control-openSUSE/pull/80
But also runs without it.
> [Review] Request from 'schubi2' @ 'yast/yast-installation/review_170601_custom_roles'

- package/yast2-installation.changes
- package/yast2-installation.spec
See https://bugzilla.suse.com/show_bug.cgi?id=1043122
- 3.2.45
Avoid accidentally installing the package in openSUSE.
> Install the yast2-registration package only in SLE (bsc#1043122)

- .travis.yml
- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
https://trello.com/c/iOESXcm7/624-5-caasp-hack-separate-data-partition
_XML format documentation for the new parameter_
CaaSP needs a separate partition for /var/lib/docker in the storage proposal, and since this would be very tricky to add to the existing proposal mechanism in yast-storage-old, we suggested to repurpose the home partition for that; it can now get another mount point from control.xml. The mechanics and the other parameters in control.xml (size etc.) are still taken from the home partition / volume.
> Enable using home partition as generic separate data partition

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/desktop_finish.rb
tested manually and it do what expected ( keep /etc/sysconfig/windowmanager ) untouched, but it still do not work, so more discussion in bnc is needed.
trello: https://trello.com/c/Nesqzfs9/1053-3-dont-write-default-desktop-if-none-selected-opensuse-only
bsc: https://bugzilla.opensuse.org/show_bug.cgi?id=1030873
> skip writing of desktop for opensuse (bsc#1030873)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/inst_disks_activate_test.rb
To be merged right after merging yast2-storage-ng 0.1.32.
Breakage in tests is expected until the new API is merged in storage-ng
> Adapt to cleaned Y2Storage::StorageManager API

- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
https://trello.com/c/SQQ1x4Bg/691-5-suse-caasp-10-p2-1051762-docker-on-xfs-by-default
This makes the filesystem type for both home and root in the storage proposal configurable: When home_fs is configurable, root_fs is only a heartbeat away, and it's trivial to add it at the same time.
Test against SLE-12 SP3:
> Make fs type for home and root configurable

- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
Notice that this will not go to master since it will be different for storage-ng.
> Merged CASP branch to to SP3

- .travis.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/clients/inst_install_inf.rb
- src/lib/installation/dialogs/complex_welcome.rb
- src/lib/installation/dialogs/product_selection.rb
- src/lib/installation/dialogs/url_dialog.rb
- src/lib/installation/widgets/language_keyboard_selection.rb
- src/lib/installation/widgets/product_selector.rb
- test/dialogs/complex_welcome_test.rb
- test/inst_complex_welcome_test.rb
- test/lib/widgets/language_keyboard_selection_test.rb
Requires https://github.com/yast/yast-yast2/pull/619, https://github.com/yast/yast-packager/pull/273 and
https://github.com/yast/yast-country/pull/138.
Move product's selection to welcome screen.
> Move product selection to welcome

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/snapshots_finish.rb
- test/snapshots_finish_test.rb
Part of https://trello.com/c/ytK5Yoe4/554-5-storageng-installation-to-root-subvolume
It depends on https://github.com/yast/yast-yast2/pull/620 and the yast2-storage-ng PR in the PBI depends on this one.
> Configure Snapper at the end of installation if requested

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
- test/lib/inst_download_release_notes_test.rb
- If any product is already selected then download the release notes only for the selected product (LeanOS). If nothing is selected download release notes for all available products - for backward compatibility with a single product medium (openSUSE).
- This is similar to the fix in registration: https://github.com/yast/yast-registration/pull/327
- 4.0.0
> Download release notes only for the selected products (bsc#1056872)

- doc/control-file.md
- [Trello Card](https://trello.com/c/Vj69gtYP/1168-5-caasp-20-hostname-via-dhcp-work-according-to-control-file)
> Added control-file documentation for dhclient_set_hostname (bsc#1054933)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/dialogs/complex_welcome.rb
- test/inst_complex_welcome_test.rb
- [Trello Card](https://trello.com/c/BKCh35fR/1191-3-1059070-upgrade-case-let-user-continue-without-selecting-a-product-request-license-agreement-later)
This is an early release just to discuss the current dialog with UI/UX experts to check as soon as possible whether we should adapt it or not.
> Do not show product selection during upgrade

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_cleaner.rb
- test/instsys_cleaner_test.rb
- Libzypp actually needs some cached repository files even during package installation. We can remove only the white listed files we know are safe to remove.
- See [bsc#1063459#c5](https://bugzilla.suse.com/show_bug.cgi?id=1063459#c25) for details
- 4.0.10
> Less eager inst-sys cleanup (bsc#1063459)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F09-start
- When you abort an installation after you have registered your product, you can't just start again as selecting any product is then blocked later
- This is not needed for a single-product add-ons, such as openSUSE, but the cleanup redirects everything to /dev/null as it complains at the first start even at SUSE Enterprise anyway
- bsc#1065167
> Calling SUSEConnect --cleanup at startup

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/lib/clients/inst_system_analysis_test.rb
I guess that a better solution for [bsc#1070996](https://bugzilla.suse.com/show_bug.cgi?id=1070996) (breaking autoyast2 and yast2-installation dependency cycle) could be used, which probably would imply moving some code between modules. For the time being, this one should work.
> Break dependency cycle

- test/test_helper.rb
Fixes [yast2-installation](https://ci.suse.de/job/yast-installation-master/198/console) build. It adds Console to the list of stubbed modules (and it sorts the list btw).
> Stub Console module

- package/yast2-installation.changes
- src/lib/installation/clients/installation.rb
- Logs this at the very beginning:
```
[Ruby] clients/installation.rb:113 System identification: "SUSE Linux Enterprise 15"
```
- The value is read from `/ets/os-release` (included in inst-sys)
- It would help me a lot in [this case](https://bugzilla.suse.com/show_bug.cgi?id=1068302#c12)
> Log the system name for easier debugging

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/remote_finish_client.rb
- startup/Second-Stage/S09-cleanup
- startup/YaST2.call
- startup/common/misc.sh
- test/remote_finish_test.rb
Alternative PR see (#659), in this PR we bring back the `xvnc.socket` enablement during the first stage when the linuxrc `vnc` option is given, the startup scripts have been adapted to stop the socket and restore it as we were doing with xinetd not supposing a problem during the `Second Stage` anymore
https://bugzilla.suse.com/show_bug.cgi?id=893501 (bug where the VNC service was originilally enabled during the installation)
https://bugzilla.suse.com/show_bug.cgi?id=1077236 (where it was removed due to a problem trying to launch the VNC Server during the Second Stage)
https://bugzilla.suse.com/show_bug.cgi?id=1078785 (To take in account, there is no `java client` anymore, so we should modify the current text (`startup/common/vnc.sh`) and adapt the script to serve the novnc javascript …
> Replace xinetd by xvnc.socket in startup scripts

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/lib/clients/inst_system_analysis_test.rb
Part of https://trello.com/c/ZFRZeyzr/240-3-ruby-code-handle-errors-during-probing
It also implements https://trello.com/c/LiG0TAoK/213-finish-adaptation-of-instsystemanalysis
Depends on https://github.com/yast/yast-storage-ng/pull/549
Bonus: bring back a very old fix
Bonus2: removal of dead code will prevent [bsc#1082854](https://bugzilla.suse.com/show_bug.cgi?id=1082854) in the master branch (still needs to be fixed for old branches)
> Better handling of aborted libstorage-ng operations

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/umount_finish.rb
- test/lib/clients/umount_finish_test.rb
Set 'ro' property for every Btrfs filesystem which is mounted as read-only at the end of the installation.
> Read-only volumes

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/update_repositories_finder.rb
- src/modules/InstFunctions.rb
- test/inst_functions_test.rb
- test/lib/update_repositories_finder_test.rb
- https://trello.com/c/syNlrXoP/1371-3-p1-1084820-handle-selfupdate-during-autoupgrade-correctly
With this PR we will show also errors getting the list of update repositories when self_update has been explicitly enabled.
Test units are missing, and if the approach is OK will also update the documentation of errors handling.
For the manual tests a Report has been added but it is not part of the PR.
> Check if self_update is explicitly enabled

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_install_inf.rb
- src/lib/installation/clients/inst_system_analysis.rb
- src/lib/installation/dialogs/url_dialog.rb
- test/inst_system_analysis_test.rb
Fixes [bsc#1082854](https://bugzilla.suse.com/show_bug.cgi?id=1082854#c3).
> Do not block autoinstallation when no disks/controllers are found

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
A fixup of #671
https://trello.com/c/WmjvFAZP/1370-5-system-roles-dialog-with-8-roles
> System roles: make the radio buttons match other dialogs, using images

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/lib/clients/inst_system_analysis_test.rb
Part of PBI: https://trello.com/c/jItiacnG/335-readd-system-wide-lock-in-libstorage-ng
See here definition of new `Yast::AbortException`: https://github.com/yast/yast-ruby-bindings/pull/215
> Use new exception

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- [bsc#1087399](https://bugzilla.suse.com/show_bug.cgi?id=1087399)
- https://trello.com/c/VasiMQRM/1401-2-bug-1087399-sle-hardcodes-text-color-making-kubic-white-on-white
Requires matching changes:
- https://github.com/yast/yast-theme/pull/85 so that SLE15 keeps looking the same
- https://github.com/openSUSE/branding/pull/90 so that Kubic looks decent
Screenshot of Kubic:
Screenshot of SLE4SAP: nothing interesting, it looks like before, which it should:
> Don't hard-code the role text color

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/umount_finish.rb
- Unmounting `/mnt` fails with "umount: /mnt: target is busy" error
- See https://bugzilla.suse.com/show_bug.cgi?id=1090018
- I have no idea why it fails, likely some `%post` script started a process or maybe YaST keeps some file opened
- To help with debugging log the `fuser` output to see which process use that mount point
- 4.0.50
> Log more details when unmounting fails (to debug bsc#1090018)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
* Related to https://github.com/yast/yast-yast2/pull/730 and https://github.com/yast/yast-packager/pull/348.
Main problems: the 'plus' signs in the list of patterns and the alignment of other elements like 'Kdump' title or 'SSH' settings.
> Fix "installation settings" support for RTL languages

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/copy_logs_finish.rb
- test/copy_logs_finish_test.rb
See also https://github.com/yast/yast-storage-ng/pull/609
This copies `/var/log/YaST2/storage-inst` to the target at the end of the installation.
Any old directory in the target system with that name is removed before so we don't get confused by upgrade after upgrade after upgrade when users submit y2logs with a bug report.
This is also a minor cleanup of that code; it had become quite messy over time.
Now all shell commands are properly logged, and there is less duplication in the code.
> Copy storage-ng XML / YAML devicegraph dump files to installation target system

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/widgets/system_roles_radio_buttons.rb
- Fixes the problem with unselected product when going back - the selected products must not be reset
- See https://bugzilla.suse.com/show_bug.cgi?id=1088660
- Less strict check for selecting the product - do not ask to select a product when there is only one product available, the selection widget is hidden in that case anyway
- 4.0.56
> Keep the selected product in the desktop selection dialog (bsc#1088660)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_system_analysis.rb
- test/lib/clients/inst_system_analysis_test.rb
For https://trello.com/c/rjLmkP8u/373-sles15-p2-1090690-storage-ng-error-encrypting-a-partition-that-was-part-of-an-md-raid.
> - disable mdadm auto assembly for installation

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/umount_finish.rb
This patch fixes the `umount_finish` client logging.
Related to bug report: https://bugzilla.suse.com/show_bug.cgi?id=1090018
Trello card: https://trello.com/c/1fXAxYLv/
> Fix unmounting logging

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
This is a backport of https://github.com/yast/yast-installation/pull/624 which has been checked in into the
wrong tree and without any update of changes and version.
> fixed crash while mounting CD-ROM

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- See https://bugzilla.suse.com/show_bug.cgi?id=1089643#c64
- Fixed possibly broken system after aborting upgrade running over SSH (caused by a partially finished rollback)
```console
*** Starting YaST2 ***
var/lib/rpm/
var/lib/rpm/.rpm.lock
var/lib/rpm/Packages
Connection to s390vsw051.suse.de closed by remote host.
Connection to s390vsw051.suse.de closed.
```
- The SSH daemon was killed too early, before the rollback was finished - the fix is to kill it at the very end of the script
- Added a comment why the file needs to be created at the end
```console
...
Restoring the registration status at /mnt, this might take several minutes...
> Beginning registration rollback. This can take some time...
Connection to dhcp253 closed by remote host.
Connection to dhcp253 closed. …
```
> Fixed broken rollback when upgrading via SSH (bsc#1089643)

- package/yast2-installation.changes
- package/yast2-installation.spec
- test/lib/clients/inst_system_analysis_test.rb
For https://trello.com/c/kkmPuoxR/94-3-1073633-l3-system-auto-mounts-ext4-partition-on-xen-pv-device-after-fs-resize-causes-yast-error.
> - adapted testsuite to change in yast2-storage-ng (bsc#1073633)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_disks_activate.rb
- test/inst_disks_activate_test.rb
Fix https://bugzilla.suse.com/show_bug.cgi?id=1098563 adding simple texts for disk activation help.
Any suggestion to improve it is welcome.
---
Related to https://trello.com/c/t6Rj03h1
> Add missing help for disk activation dialog

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- test/copy_files_finish_test.rb
From https://bugzilla.suse.com/show_bug.cgi?id=1062297
> after installation I could not find /etc/YaST2/build
> There is no more /build - it has been integrated into /media. And yast needs to copy it in place of /build
~~This RFC is to know your point of view about what to do with the destination of `/media.1/media` in the installed system:~~
~~* Keep as it is: `/build`~~
~~* Change to `/media`~~
~~* Copy to both: `/media` and `/build` (does have sense???)~~
This PR change the source from `/media.1/build` to `/media.1/media` and destination to `/media`, but also keeping `/build` for backward compatibility with other (not adapted yet) tools, as @lslezak suggested in #yast IRC channel.
---
Related to https://trello.com/c/O0F6RkaQ
> Fix path to media/build info file

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
> The backup only will be restored when the ID and VERSION_ID matches in
both, the current and backed os-release file.
> Do not restore old backups when upgrade fails

- Rakefile
- Check also the syntax of the shell scripts
- This should avoid bugs like in #745 
- Travis should fail with an error, see [this example build](https://travis-ci.org/yast/yast-installation/builds/432959542#L1430-L1431)
> Check also the syntax of the startup scripts

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
When there is only one role available, directly applies it and skip the dialog.
Related to https://trello.com/c/uzNWUsjG/337-fate-324713-optimize-system-role-handling-dont-show-system-role-dialog-when-only-one-or-none-system-role-is-available
> Skip the roles' selection dialog

- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
> Related to fate#324713 and [bsc#1112564](https://bugzilla.suse.com/show_bug.cgi?id=1112564), avoid also to show the role
selection dialog user is going back and there is only one role
available.
> Skip role selection dialog when there is only one role available (:back direction)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- src/lib/installation/system_role.rb
- test/lib/clients/inst_system_analysis_test.rb
- test/select_system_role_test.rb
- The selected role was not remembered, `Installation::SystemRole.current` returned `nil` even after selecting a role.
- This makes troubles with the role finish clients, they are not executed because the finish client thinks nothing was selected:
```
[Ruby] installation/system_role.rb:175 There is no role selected so nothing to do
```
- Fixed a problem with a missing mock, running `rake test:unit` executed the `/usr/lib/YaST2/bin/mask-systemd-units` command resulting in displaying this dialog (sorry, Czech only):
- Fixed by mocking all `Yast::Execute.locally!` calls
- 4.1.21
> Remember the selected role (related to FATE#325834), fixed testsuite

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/include/installation/inst_inc_first.rb
- startup/common/language.sh
Force the installer to use `fbiterm`.
See also yast/yast-country#192 and yast/yast-autoinstallation#477.
> Force the installer to use fbiterm

- .travis.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_cleaner.rb
- startup/First-Stage/F08-logging
- test/instsys_cleaner_test.rb
- Clean the libzypp cache when running in graphical mode with less than 1GB RAM (in text mode keep the current limit 640MB), this avoids crashes on low memory systems.
- Updated the glob list, the `appdata-icons.tar.gz` file now also has a hash prefix, just like the other files. (See the [repo data](https://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/) for Leap 15.1.)
- 4.1.32
> More aggresive inst-sys cleaner (bsc#1118643)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_extrasources.rb
To avoid selecting the driver packages again if user deselected them during installation we need to mark the installation repositories as "known".
See more details in the links below.
Travis fails because of the new dependency, the package builds fine locally.
- https://github.com/yast/yast-packager/wiki/Selecting-the-Driver-Packages
- https://bugzilla.suse.com/show_bug.cgi?id=953522
- https://github.com/yast/yast-packager/pull/401
> Save the used repositories at the end of installation (bsc#953522)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- https://trello.com/c/Hp7r298L
- https://bugzilla.suse.com/show_bug.cgi?id=1127182
yast2.rpm that normally owns that dir may not be there
I've tested with an unregistered SLES installation (Build178.3) that the bug exists without the fix and disappears with the fix.
> Mkdir /etc/YaST2 before copying files to it (#1127182)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
https://trello.com/c/XddgyRZS
https://bugzilla.suse.com/show_bug.cgi?id=1047470
The fix is: in `check_network`, which is called for SSH installations, only check `$DISPLAY` when `Textmode` is not set. 
Additional small fix: no need to check the qt plugin if we haven't selected it in the first place. Note that some logical combinations don't assign `Y2_MODE`. That is fine because for SSH, it is preset to ncurses before calling this function.
> Respect Textmode=1 when installing over SSH with a DISPLAY (bsc#1047470)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/desktop_finish.rb
- test/desktop_finish_test.rb
Editing the `DISPLAYMANAGER` variable in `/etc/sysconfig/displaymanager` does not make effect anymore. Instead, `update-alternatives` should be used to change the default display manager, see [release notes for Leap 15.0](https://doc.opensuse.org/release-notes/x86_64/openSUSE/Leap/15.0/index.html#general).
The X11 team already [fixed the XDM package](https://build.opensuse.org/request/show/674644) to not include this variable in `/etc/sysconf/displaymanger` file, so `yast2-sysconfig` editor will not show this value anymore.
But `yast2-installation` is still writing the `DISPLAYMANAGER` value in its `desktop_finish` client.
* https://bugzilla.suse.com/show_bug.cgi?id=1125040
* https://trello.com/c/FSAwjaC1/769-1-osdistribution-p3-1125040-install-yast2-alternatives-module-by-default-in-addit …
> Do not write displaymanager value

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/dialogs/complex_welcome.rb
- test/dialogs/complex_welcome_test.rb
- The side bar steps were translated only after pressing the `Next` button
- They should be updated immediately after changing the language
- https://bugzilla.suse.com/show_bug.cgi?id=1128153
- A similar issue was fixed in #762 
- Added unit test
- Tested manually in Leap 15.1 - the sidebar is updated immediately (see the screencast below)
- Tested manually in SLE15-SP1 - the sidebar is not displayed there, no regression there
> Retranslate the side bar steps (bsc#1128153)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
The installation summary shows a list of patterns to install, but if you go back until the Role Selection screen and then go forward again without changing the role, the list of patterns shown by the installation summary changes (there are much less patterns).
* https://bugzilla.suse.com/show_bug.cgi?id=1126517
* https://trello.com/c/OrkgoQYI/795-important-osdistribution-p2-1126517-patterns-are-not-selected-anymore-when-going-back-to-the-system-role-selection-screen
The packages/patterns automatically selected by the solver should be deselected before calling the solver again. Otherwise, the solver does not select the same list of patterns (a bug with the solver?).
* Tested manually.
> Fix packages and patterns selection

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_license.rb
After the changes made for fate#324053 / jsc#SLE-4173, the license for the base product will be located at `/usr/share/licenses/product/base` instead of `/etc/YaST2/licenses/base`.
---
Related to https://github.com/yast/yast-yast2/pull/907
> Update hard-coded fallback path to licenses directory 

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
This reverts
- https://github.com/yast/yast-installation/pull/778
- https://github.com/yast/yast-installation/pull/785
as they were causing too much collateral damage.
> revert  SSH textmode patches (bsc#1129375, bsc#1047470)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
This reverts
- https://github.com/yast/yast-installation/pull/779
- https://github.com/yast/yast-installation/pull/786
as they were causing too much collateral damage.
> revert SSH textmode patches (bsc#1129375, bsc#1047470)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- test/lib/clients/inst_complex_welcome_test.rb
Having multiple products in a single repository (i.e. openSUSE and Kubic), `system-installation()` could provide the "wrong" one during a network installation, ending with conflicts between product and patterns.
- https://bugzilla.suse.com/show_bug.cgi?id=1124590
- https://trello.com/c/RPnSpewA/808-3-tw-kubic-1124590-optionally-hardcode-the-product-name-in-the-controlxml
Originally proposed by @lslezak, 
> to hardcode the product name in the control.xml 
So, the installer would select the right product **without asking to user**.
- *Added a new unit test*
- https://github.com/yast/yast-installation-control/pull/79
> Allow to preselect the product

- Dockerfile
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/clients/inst_ntp_setup.rb
- src/lib/installation/dialogs/ntp_setup.rb
- src/lib/installation/widgets/ntp_server.rb
- test/dialogs/ntp_setup_test.rb
- test/lib/widgets/ntp_server_test.rb
The screen for configuring NTP, currently available at `yast2-caasp`, should be able to be used for whatever role.
*Short description of the original problem.*
- http://bugzilla.suse.com/show_bug.cgi?id=1129095
- https://trello.com/c/8uqCahT2/875-3-make-yast2caasp-kubeadm-ntp-screen-more-genericly-available
_Move_ the dialog to `yast2-installation`.
- Also _moved_ the unit test available in `yast2-caasp`
- Tested manually in TW and Kubic
* TW
| NTP Setup | Validation |
|-----------|------------|
|![Screenshot_test_2019-03-28_22:52:27](https://user-images.githubusercontent.com/1691872/55224791-26c2e180-5209-11e9-9ca0-8450110ab8ed.png)|![Screenshot_test_2019-03-28_22:52:45](https://user-images.githubusercontent.com/1691872/55224790-26c2e180-5209-11e9-8310-afe8e5bcd711.png)|
* KUBIC
| NTP …
> Add a NtpSetup installation dialog

- package/yast2-installation.changes
- package/yast2-installation.spec
- test/test_helper.rb
- `BuildRequires: yast2-ntp-client` caused a dependency cycle and must be removed.
- It was needed only for the unit tests, can be replaced by a stub module
- The disadvantage is that RSpec then cannot verify if the mocked methods really exist, but there is probably no better and simple solution
> Removed BuildRequires: yast2-ntp-client (causing dependency cycle)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
https://trello.com/c/gjV8SydY
https://bugzilla.suse.com/show_bug.cgi?id=1128385#c4
(the "reopen" case starting at comment #4)
https://openqa.opensuse.org/tests/913479
https://openqa.opensuse.org/tests/913480
No autologin even with a full-fledged KDE Plasma or GNOME desktop.
Pkg target already shut down (`Pkg::TargetFinish`), i.e. no packages known to libzypp on the target system, i.e. also no display manager that supports autologin, so no autologin configuration is written.
Change the order in `inst_finish.rb`: Make sure `pkg` is _after_ `users`.
Manual test with the ISO from the OpenQA test case plus the changed `inst_finish.rb` bind-mounted.
> Make sure pkg target is alive as long as needed

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
- test/file_from_url_test.rb
Has also been tested by the reporter.
> Sle 15 sp1 bsc 1132915

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- test/copy_files_finish_test.rb
When using the multipath optioin *user_friendly_names* during installation, the following config files must also be copied to the installed system: */etc/multipath.conf* and */etc/multipath/bindings*. Otherwise, names persistence is not guarantee.
* https://www.suse.com/support/kb/doc/?id=7001133
Needed for:
* https://bugzilla.suse.com/show_bug.cgi?id=1133045
* https://trello.com/c/3re8LvvF/1049-autoyast-hw-probing-behavior-vs-scripts
Client *inst_files_finish* has been adapted to copy multipath config files into the target system.
> Copy Multipath config files

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
In the text mode, the proposal summary lost the focus when user makes changes using the available options (for example, toggling the firewall settings). The focus is changed to the <kbd>Change...</kbd> combobox.
* https://bugzilla.suse.com/show_bug.cgi?id=1142353
Set the focus in the mentioned area (which is a `RichText`) each time that the `input_loop` start again.
The first time that the user arrives to this dialog, the focus is captured by the first available option inside the summary (`Software` in the screenshot attached), instead of the `Release Notes` _button_.
Tested manually, via driver update.
<p align="center"><sub>The installation summary, with the focus in the Software option</sub></p>
> Keep focus in the RichText widget for the proposal installation summary

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- test/lib/clients/inst_complex_welcome_test.rb
Recently, the `select_product` option was added to the control file to allow **forcing** the base product selection when having multiple products in a single repository (see https://github.com/yast/yast-installation/pull/790).
But seems that the feature was not fully implemented and the installer only avoids displaying the product selector, but not marking the forced product as selected, raising an internal error when trying to access to `#installation_package`.
* https://bugzilla.suse.com/show_bug.cgi?id=1143943
* https://trello.com/c/YuiJfYBt/1201-ostumbleweed-p1-1143943-build-20190801-undefined-method-installationpackage
To select the **foced** product properly.
:warning: **Requires `yast2 4.2.17` - https://github.com/yast/yast-yast2/pull/954**
See …
>  Fix the forced base product selection (3/3)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/clients/inst_system_analysis.rb
- startup/YaST2.Second-Stage
- startup/YaST2.call
- startup/common/vnc.sh
- test/ssh_config_test.rb
- test/ssh_import_auto_test.rb
- test/ssh_importer_presenter_test.rb
- test/test_helper.rb
It was useful in 2006 when X.org 6 and X.org 7 had different places for files
- https://bugzilla.suse.com/show_bug.cgi?id=1144627
textdomain:
- https://bugzilla.suse.com/show_bug.cgi?id=1130822
> Stop using obsolete XVersion; check textdomain presence

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
The [change introduced in `4.2.7`](https://github.com/yast/yast-installation/pull/806/commits/28e689991946abfb5bc89ca5d25b82cc635d876f) improves nothing. Even worst, now the focus it is always caught by the proposal installation summary, even when the user choose an action from the `Change...` _actions button_.
Undo the change and wait 
> for the innovation and renovation regarding LibYUI and the YaST UI — https://lizards.opensuse.org/2019/08/14/yast-sprint-82/
---
Related to https://github.com/yast/yast-installation/pull/806
> Undo the change done in 4.2.7

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/pre_umount_finish.rb
- test/lib/clients/pre_umount_finish_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1149011
At the end of the installation, switching the X server to text console and then back leaves the X server unresponsive to any input. (This workflow is part of openqa collecting logs.)
YaST deleted `/mnt/run` at the end of the installation in an attempt to fix [bsc#1071745](https://bugzilla.suse.com/show_bug.cgi?id=1071745).
That's a really bad idea as that is a bind-mounted directory. This way `/run` got cleaned up as well.
The fix is needed in conjunction with [bsc#1136463](https://bugzilla.suse.com/show_bug.cgi?id=1136463).
Do not do this.
> do NOT remove /mnt/run, it's a mounted directory (bsc#1149011)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/widgets/product_selector.rb
- test/lib/clients/inst_complex_welcome_test.rb
- test/widgets/product_selector_test.rb
- Adjust the product selection in the welcome screen for the online medium installation
- The products are read from the `control.xml` file
- Updated selecting the product
- https://jira.suse.com/browse/SLE-7214
- 4.2.14
> Support for the online installation medium (jsc#SLE-7214)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/umount_finish.rb
https://bugzilla.suse.com/show_bug.cgi?id=1140171
At the end of the installation, some processes might lock up when fips is enabled.
Do not kill haveged.
It's needed to avoid security relevant processes to lock up due to insufficient randomness.
- related change in inst-sys: https://github.com/openSUSE/installation-images/pull/333
- Scrum card: https://trello.com/c/PiMSEWGo
> do not stop haveged process (bsc#1140171)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/widgets/product_selector.rb
- test/lib/clients/inst_complex_welcome_test.rb
- test/widgets/product_selector_test.rb
- Adapt the product selection and initialization for the offline installation medium
- Do not allow changing the selected base product when going back (we would need to remove the previous base product repository which might be tricky if some addons have already been added)
- https://jira.suse.com/browse/SLE-7101
- 4.2.16
> Support for the offline installation medium (jsc#SLE-7101)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- test/select_system_role_test.rb
Some time ago, the list of available roles grown enough to start not fitting in the role selection dialog. To fix it, the list was embedded in a scrollable `RichText` widget since [libyui](https://github.com/libyui/libyui) didn't offer a better option (see https://github.com/yast/yast-installation/pull/671, [bsc#1084674](https://bugzilla.suse.com/show_bug.cgi?id=1084674), [bsc#1086187](https://bugzilla.suse.com/show_bug.cgi?id=1086187)).
As part of a [YaST UI improvements](https://gist.github.com/shundhammer/1bc79af7d1a31892bd977678bc2af2c1) a new `SingleItemSelector` (see https://github.com/libyui/libyui/pull/148) has been added, which is a much better solution to display the roles list.
To update the role selection dialog using the new widget and removing the old code.
* Unit tests …
> Improve the role selection dialog

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
The proposal installation summary back to the top after performing any change, not preserving the scroll.
* Related to the behavior described at https://bugzilla.suse.com/show_bug.cgi?id=1143558
* https://trello.com/c/ZocPUtvz/1330-3-use-save-restore-scrolling-in-installation-proposal
The proposal summary, which is being held by a `RichText` widget, is re-drawn after making a change. So, it's actually new content.
To use [the new `:VScrollValue` property](https://github.com/libyui/libyui/pull/149) added to the  [libyui](https://github.com/libyui/libyui) RichText widget as part of the [YaST UI improvements](https://gist.github.com/shundhammer/1bc79af7d1a31892bd977678bc2af2c1). Taking into account that the content could be longer or shorter after each change, the solution is not completely …
> Save and restore properly the proposal vertical scroll

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/include/installation/misc.rb
- src/lib/installation/clients/copy_files_finish.rb
- test/copy_files_finish_test.rb
When copying files from inst-sys to the target system we are also removing the /etc/install.inf file if the second stage is not required. That problem alone would not affect the installation if the file is read before removing it because we usually cache the state. But it get worst if we reset the Linuxrc state indiscriminately as we currently do.
- https://bugzilla.suse.com/show_bug.cgi?id=1157476
By now, we will just drop that removal of the file from inst-sys and will maintain the reset of internals. Mainly because the method is also used during the second stage, and in combination with yast/yast-yast2#984 we should be able to re-read the file.
> Do not remove /etc/install.inf from inst-sys (bsc#1157476)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_addon_update_sources.rb
- src/lib/installation/clients/inst_extrasources.rb
- src/lib/installation/clients/inst_modules_extensions.rb
- src/lib/installation/clients/inst_prepare_image.rb
- src/lib/installation/update_repository.rb
- src/modules/ImageInstallation.rb
- test/lib/clients/inst_extrasources_test.rb
- test/lib/inst_modules_extensions_test.rb
- test/update_repository_test.rb
Replacing old Pkg.ResolvableProperties()and Pkg.ResolvabeDependencies() calls by Y2Packager::Resolvable.any? and Y2Packager::Resolvable.find in order to save memory.
> Decreasing required memory

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/Second-Stage/S07-medium
- startup/Second-Stage/S09-cleanup
https://bugzilla.suse.com/show_bug.cgi?id=1160890
https://trello.com/c/3Y9HSV8m
`/bin/systemctl` symlink is gone.
Don't use it.
> don't use /bin/systemctl compat symlink (bsc#1160890)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_upgrade_urls.rb
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/clients/inst_upgrade_urls_test.rb
- test/lib/upgrade_repo_manager_test.rb
- Better work with the old repositories and services
- Related to
- https://bugzilla.suse.com/show_bug.cgi?id=1159433
- https://github.com/yast/yast-yast2/pull/1010
- https://github.com/yast/yast-packager/pull/502
- https://github.com/yast/yast-update/pull/147
- Added unit tests
- The `clients/inst_upgrade_urls.rb` file has been completely reimplemented (1210 deletions :open_mouth:)
- It is probably easier to review the complete new file instead of the diff ([see here](https://github.com/yast/yast-installation/blob/old_repositories/src/lib/installation/clients/inst_upgrade_urls.rb))
- The old client was able to configure the network if needed, but as we now try to configure the network automatically at the beginning this is not needed and that functionality has been …
> Old repositories

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
`yast firstboot` gets killed by signal HUP because there's a getty process running concurrently on the same console.
- https://bugzilla.suse.com/show_bug.cgi?id=1157233
- https://trello.com/c/yzMr62XT
Prevent systemd from starting a getty service on hvc0 and ttyAMA0 which are typical serial consoles on ppc64 resp. aarch64.
https://bugzilla.suse.com/show_bug.cgi?id=935965#c15
> no getty on hvc0 & ttyAMA0 before Yast2-Firstboot (bsc#1157233)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_upgrade_urls.rb
https://bugzilla.suse.com/show_bug.cgi?id=1084015
This puts en_US "translations" which are really fixes for broken English or broken translations back into the sources.
```po
#
msgid ""
msgstr ""
"Project-Id-Version: YaST (@memory@)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-12-19 02:28+0000\n"
"PO-Revision-Date: 2008-05-16 13:44+0200\n"
"Last-Translator: proofreader <i18n@suse.de>\n"
"Language-Team: English <i18n@suse.de>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;"
#. TRANSLATORS: help text 3/3
#: src/lib/installation/clients/inst_upgrade_urls.rb:264
msgid "<p>To change the URL, click on the <b>Change...</b> button.</p>"
msgstr "<p>To change the URL, …
```
> Fixed user-visible messages (bsc#1084015)

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
This is a port of https://github.com/yast/yast-installation/pull/834 to master.
`yast firstboot` gets killed by signal HUP because there's a getty process running concurrently on the same console.
- https://bugzilla.suse.com/show_bug.cgi?id=1157233
- https://trello.com/c/yzMr62XT
Prevent systemd from starting a getty service on hvc0 and ttyAMA0 which are typical serial consoles on ppc64 resp. aarch64.
https://bugzilla.suse.com/show_bug.cgi?id=935965#c15
> don't start getty on hvc0 & ttyAMA0 before Yast2-Firstboot (bsc#1157233)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/updates_manager.rb
- test/updates_manager_test.rb
Using the self-update is not possible to replace the `control.xml` file unless you craft a special package that contains that file in the root filesystem. This PRs extends the the self-update mechanism to update the `/control.xml` file with `/usr/lib/skelcd/CD1/control.xml`, which is where `skelcd-control-CAASP`, `skelcd-control-Kubic`, `skelcd-control-leanos`, `skelcd-control-MicroOS` and `skelcd-control-openSUSE` put the control file.
> Self-update control file

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/dialogs/ntp_setup.rb
- test/dialogs/ntp_setup_test.rb
Use the new `Y2Network::NtpServer` when proposing the default values for NTP servers.
Related PR: https://github.com/yast/yast-network/pull/1039
> [SLE-7188] Default to SUSE ntp servers

- Rakefile
- bin/yupdate
- doc/yupdate.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- test/helpers.rb
- test/test_helper.rb
- test/yupdate/gem_installer_test.rb
- test/yupdate/inst_sys_test.rb
- test/yupdate/overlayfs_test.rb
- Related to https://github.com/yast/yast-rake/pull/76
- https://bugzilla.suse.com/show_bug.cgi?id=1162826
- Patching the installer is not easy, building DUD for several packages takes time and is not trivial
- Let's have a simple script in the inst-sys called `yupdate` which can download the sources directly from GitHub and install them to the inst-sys
- To make it easier allow patching from a local Git checkout (without need to push every single change to GitHub)
- See more details in the `yupdate.md` documentation file
- Added some unit tests, but only small part is covered (BTW making the code coverage work was a bit tricky...)
- As mentioned in the script, the reason why all classes are in a single file is that it will make installing or updating the script with …
> Added "yupdate" script

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
- test/lib/clients/inst_download_release_notes_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1158287
https://trello.com/c/vmm7flFk/
The release notes for add-on products were not shown any more.
Don't use `Product.with_status()` because that uses `all_products()` without the `force_repos` parameter.
In the case of online media, this means that it only uses products from the control file which means you will only get base products.
Now using `all_products()` directly, but _with_ the `force_repos` parameter, so we get all products from all repos; and now we also get SLE-HA, so we can check it for release notes.
> Show Release Notes for Add-On Products

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_welcome.rb
trello: https://trello.com/c/5h7u5BGH/1697-sles15-sp2-p3-1163347-firstboot-does-not-warn-the-user-before-abort-in-welcome
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1163347
Issue: no confirmation when aborting
solution: use standard AbortConfirm method
> Abort confirm

- bin/yupdate
- Write trailing newline to the `/etc/install.inf` file so the values added later properly start on a new line
- Method `unescape_path` is static and needs the class name
- No version bump, there are some more changes in the queue
> yupdate fixes

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/instsys_packages.rb
- src/lib/installation/selfupdate_verifier.rb
- test/fixtures/inst-sys/packages.root
- test/inst_update_installer_test.rb
- test/instsys_packages_test.rb
- test/selfupdate_verifier_test.rb
- The inst-sys does not contain the RPM DB with the installed packages so the self-update code just blindly downloads and installs everything it finds without any dependency checks.
- YaST gets the self update repository URL either from the SCC or uses the default from the `control.xml`. This way ensures the self-update repository contains the right packages for the installer.
- However, users can use their custom self-update repository (e.g. SMT/RMT) and there is a possibility that by mistake the users could use a wrong repository, e.g. SP1 repository in SP2
- We got even an [L3 bug](https://bugzilla.suse.com/show_bug.cgi?id=1163084) with this mistake
- The inst-sys contains the list of the installed packages in the `/.packages.root` file
- To avoid false positives (as there might be a …
> Added selfupdate verification (bsc#1163084)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/common/language.sh
- During firstboot, when RC_LANG is 'POSIX' we try to export LANG as POSIX.UTF-8 which is not valid.
- https://trello.com/c/eMiBCnv0/1813-sle12-sp4-l3-1169017-yast2-firstboot-cannot-configure-network-if-disabled-confused-by-posixutf-8
- Fallback to en_US.UTF-8 when RC_LANG is 'POSIX' or 'C'
> use LANG=UTF-8 in case of RC_LANG=POSIX

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/common/language.sh
It cherry picks #851 
I tried to sync SLE-12-SP5 but there are too many changes and some of them related to CaaSP, so, it seems we usually just cherry pick the changes.
> use LANG=UTF-8 in case RC_LANG is 'POSIX' or 'C'

- autoyast_desktop/deploy_image.desktop
- autoyast_desktop/ssh_import.desktop
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/icons/hicolor/scalable/apps/yast-image-deployment.svg
- src/icons/hicolor/scalable/apps/yast-ssh-import.svg
Despite some missing icons were already restored (see https://github.com/yast/yast-autoinstallation/pull/585), the bug report still open because icons for `Image deployment` and `SSH Key Import` are missing yet.
* https://trello.com/c/8rb9XQHD
* https://bugzilla.suse.com/show_bug.cgi?id=1168123
* https://bugzilla.opensuse.org/show_bug.cgi?id=1168281
_Restore_ them using icons that were previously available in https://github.com/yast/yast-theme/commit/afa341066b9851808fbaa25756470cd119d41bfd
The icon for  `Image deployment`  is
> actually a copy of the scalable yast-software icon, since
different versions of `yast-deploy_image`were found, namely
> 
> 
> * 22x22 (a green box with a red `N`)
> 
>   yast/yast-theme@afa3410#diff-6c014aa4c0cb18ea190bfc7b2d2b70a8
> 
> * 32x32 (a link to …
> Restore some missing icons

- package/yast2-installation.changes
- src/lib/installation/clients/inst_upgrade_urls.rb
- test/ssh_import_auto_test.rb
While reviewing changes done in https://github.com/yast/yast-registration/pull/466, we decided to improve the UX (although I'd say _cognitive improvement_) by labeling slightly different the _Current Status_ column.
To use _Action_ instead _Current Status_ and re-labeling accordingly.
| Before | After | 
|-|-|
| Current Status | Action |
| Toggle Status | Toggle Action |
| Change... | Change URL... |
| Removed  | Remove |
| Enabled | Enable |
| Disabled | Disable |
| Unknown | Keep |
No version bump required
Only tested manually
<details>
<summary>Click to show/hide screenshots when running in graphical mode</summary>
---
| Dialog | Help |
|-|-|
| ![Screenshot_opensusetumbleweed_2020-06-12_15:43:48](https://user-images.githubusercontent.com/1691872/84515174-0541fe80-acc4-11ea-96fb-6e0e816c …
> Replace some labels in the Previously Used Repositories dialog

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- test/copy_files_finish_test.rb
Copy the NVMe hostnqn and hostid config files from the installation system to the target system during installation. Otherwise the nvme-cli package has generated different config files which can lead to trouble.
This patch does not generate the files during installation. That still has to be implemented.
For https://bugzilla.suse.com/show_bug.cgi?id=1172853 and https://trello.com/c/xHxU2p3J/1910-2-sles15-sp2-p2-1172853-no-nvme-hostnqn-or-hostid-in-the-install-system.
> copy NVMe hostnqn and hostid

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F08-logging
This is a fixup for #864.
For a normal installation, install.inf will declare `Cmdline` but @teclator found that virt-install will omit it. The installation will fail.
> Fix "Cmdline: parameter not set" for virt-install (bsc#1172139)

- test/lib/upgrade_repo_manager_test.rb
Fix UpgradeRepoManager tests. It looks like a side effect of https://github.com/yast/yast-yast2/pull/1071.
Open question: do we need to adapt the `UpgradeRepoManager` API?
> Fix UpgradeRepoManager tests

- doc/control-file.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/installation.rb
YaST installer and YaST Firstboot look very different because they are using different layout configuration.
YaST installer allows a limited configuration of its layout by using the *installation_ui* setting in the control file. Now there are more possible layout configurations thanks to the new *installation_layout* settings, see https://github.com/yast/yast-installation-control/pull/99.
* Part of https://trello.com/c/cWUeijfl/1962-2-round-unify-firstboot-look-and-feel-with-installer
* Related to https://jira.suse.com/browse/PM-1998
There is a new helper class (`UI::Wizards::Layout`) provided by *yast2* that allows to configure the layout according to the control file settings. That class is now used to configure the layout.
* See https://github.com/yast/yast-yast2/pull/1080
* See …
> Use wizard layout

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/cio_ignore.rb
- test/cio_ignore_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1168036
- https://trello.com/c/if9ZgetC
yast should offer the option to turn off device autoconfig on s390. Similar to the cio settings.
This needs https://github.com/yast/yast-bootloader/pull/612 to make it possible to adjust the `rd.zdev` kernel option.
> handle device autoconfig setting in summary screen (bsc#1168036)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/pre_umount_finish.rb
- https://trello.com/c/uvvRtBXL
- https://bugzilla.suse.com/show_bug.cgi?id=1174964
Save random pool for systemd to the correct location `/var/lib/systemd/random-seed`.
Why not call `/usr/lib/systemd/systemd-random-seed save`?
- `systemd-random-seed` is not documented and it's in systemd's private `/usr/lib/systemd` dir - so its interface might change
- `/var/lib/systemd/random-seed` is quite stable (unchanged since we introduced systemd in SLE12)
- our use case here is copying the random seed from one system to another while  `systemd-random-seed` saves and loads it on the same system
> save random pool to /var/lib/systemd/random-seed (bsc#1174964)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/update_repository.rb
- test/update_repository_test.rb
- See https://bugzilla.suse.com/show_bug.cgi?id=1175614
- The inst-sys contains the list of included packages (and their versions) in the `/.packages.*` files
- However, after YaST applies the self-update packages that is not true anymore
- Additionally it would help with debugging some problems if we could quickly get the list of updated packages in the inst-sys (could be used for debugging bug https://bugzilla.suse.com/show_bug.cgi?id=1175374)
- Write the list of the updated packages to the `/.packages.self_update` file using the same format as the installation-images use for the other `/.packages.*` files.
- Added a unit test
- Manually tested in the SP2 installer, after running the self-update step the `/.packages.self_update` file contained these lines:
```
libsolv-tools …
```
> Write the self-update packages to `/.packages.self_update` (bsc#1175614)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_install_inf.rb
- test/inst_install_inf_test.rb
During an autoinstallation, if the networking section only contains the [keep_install_network](https://documentation.suse.com/sles/15-SP2/single-html/SLES-autoyast/#CreateProfile-Network) option it should copy the network configuration from linuxrc to the target system. This is not the case of the hostname option which is lost.
- https://bugzilla.suse.com/show_bug.cgi?id=1177768
Write the linuxrc hostname and proxy configuration also during an autoinstallation.
It needs https://github.com/yast/skelcd-control-leanos/pull/67 in order to be run.
> AY: write linuxrc proxy and hostname to inst-sys

- bin/yupdate
- package/yast2-installation.changes
- It is needed for updating yast2-theme
- No package version bump, let's release it with other "real" fix
> yupdate - make also /usr/share/icons writable

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/dialogs/complex_welcome.rb
- test/dialogs/complex_welcome_test.rb
- https://trello.com/c/3NmLtDUr
- https://bugzilla.suse.com/show_bug.cgi?id=1179094
- https://bugzilla.suse.com/show_bug.cgi?id=1176424
When the full media contain only a single product, yast crashes trying to display the license.
The problem starts here:
- https://github.com/yast/yast-installation/blob/master/src/lib/installation/clients/inst_complex_welcome.rb#L172-L198
`available_base_products` returns the list of products but for the offline media ('full media') the returned type is a list of `Y2Packager::ProductLocation` classes which are not compatible with `Y2Packager::Product` which might also be returned and are in fact implicitly assumed in (part of) the code.
The issue arises when there's only a single product as then yast tries to skip the product selection and to show a …
> fix full media product selection (bsc#1179094, bsc#1176424)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_cleaner.rb
- test/instsys_cleaner_test.rb
- Do not cleanup the libzypp cache when the system has low memory, incomplete cache confuses libzypp later
- See https://bugzilla.suse.com/show_bug.cgi?id=1179415#c9
- That cache cleanup saved ~5MB in a Tumbleweed installation (DVD only), if we really need it then we need to improve the logic a lot (see https://bugzilla.suse.com/show_bug.cgi?id=1179415#c14)
> Do not cleanup the libzypp cache (bsc#1179415)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_cleaner.rb
- test/instsys_cleaner_test.rb
- Requested in https://bugzilla.suse.com/show_bug.cgi?id=1179415#c16
- Do not cleanup the libzypp cache when the system has low memory, incomplete cache confuses libzypp later
- See https://bugzilla.suse.com/show_bug.cgi?id=1179415#c9
- See PR #900
> [SP2] Do not cleanup the libzypp cache (bsc#1179415)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/snapshots_finish.rb
- test/snapshots_finish_test.rb
Adapt to `FsSnapshot` API changes introduced in yast/yast-yast2#1125.
> bsc#1180142: do not use 'installation-helper' to create snapshots

- src/lib/installation/widgets/polkit_default_priv.rb
It adds missing `require` detected by public Jenkins jobs while running the test suite. 
See #906 / https://ci.opensuse.org/job/yast-yast-installation-master/142/consolen and #920 / https://ci.opensuse.org/job/yast-yast-installation-master/143/
> fix missing require

- .github/workflows/ci.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/console.rb
- src/lib/installation/console/commands.rb
- src/lib/installation/console/gui.rb
- src/lib/installation/console/menu.rb
- src/lib/installation/console/menu_plugin.rb
- src/lib/installation/console/plugins.rb
- src/lib/installation/console/plugins/console_button.rb
- src/lib/installation/console/plugins/shell_command.rb
- src/lib/installation/console/tui.rb
- src/lib/installation/dialogs/complex_welcome.rb
- src/lib/installation/widgets/console_button.rb
- test/lib/dialogs/complex_welcome_test.rb
The goal is to enable configuring some devices (network, proxy) or setting some installer options in special cases. Usually it should not be needed but in some rare cases it would nice to offer some hidden configuration options.
- [Internal Trello card](https://trello.com/c/TOdZIh98/2209-5-continue-with-an-easy-to-way-to-configure-and-in-installer)
- Jira: [SLE-16263](https://jira.suse.com/browse/SLE-16263), [SLE-16358](https://jira.suse.com/browse/SLE-16358)
Because it's too late to change the dialogs in the SLE15-SP3 (and Leap 15.3) the push button is displayed only in a Tumbleweed installation. In SLE15-SP3 we will use a keyboard shortcut (needs https://github.com/yast/yast-ruby-bindings/pull/270), that will also work in Tumbleweed.
In a plain VGA console (without KMS) the unicode …
> The Installer Console (SLE-16263, SLE-16358)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/kernel_finish.rb
The kernel_finish client does some udevadm calls from the target system (chroot) which do not have any effect at all.
- https://bugzilla.suse.com/show_bug.cgi?id=1180535
Remove unnecessary calls from kernel_finish as since /dev and /run are shared and since (https://github.com/systemd/systemd/pull/11346) them are completely useless.
> Remove useless udevadm calls from kernel_finish client

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_update_installer.rb
- src/lib/installation/selfupdate_cleaner.rb
- test/fixtures/self-update-inst-sys/download/yast_000
- test/fixtures/self-update-inst-sys/download/yast_001
- test/inst_update_installer_test.rb
- test/lib/selfupdate_cleaner_test.rb
This PR adds logic to the installer to clean-up the unused self-update files.
|            | uncompressed | compressed | total     |
|----------|--------------------:| ----------------:| ----------:|
|Before | 262MB             | 92MB           | 354MB |
|After    | 58MB               | 18MB           | 76MB   |
> Clean unused self-update files

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F08-logging
- startup/First-Stage/F09-start
- startup/First-Stage/F10-cleanup
- Remove the libzypp cache symlink when YaST is restarted
- Related to https://github.com/yast/yast-packager/pull/559
- Improved `memsample` script handling
- Do not start it again if it is already running (might happen if YaST is started again after crash)
- Stop it when YaST finishes
- 4.3.34
> Remove the libzypp cache symlink (bsc#1182928)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/console/plugins/shell_command.rb
- See https://bugzilla.suse.com/show_bug.cgi?id=1183648
- Use the `dash` shell in the expert console to avoid job control error messages which `bash` prints at start:
```
bash: cannot set terminal process group (1980): Inappropriate ioctl for device
bash: no job control in this shell
```
- The `dash` shell is present in the inst-sys, but to make the code more robust it checks if it is present and fallbacks to `bash` or even `sh`.
- The problem is that in GUI to have a terminal window we have to run `bash` in background in an `xterm` window. And if from that terminal you want to start `bash` again than it will complain with the error messages above because the terminal process group is already taken by that `bash` running in background.
- Unfortunately `bash` does not have any command line …
> Expert console: use "dash" shell (bsc#1183648)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/console.rb
- src/lib/installation/console/plugins/shell_command.rb
- Fixes frozen `vim` when running from shell in the expert console in text mode
- https://bugzilla.suse.com/show_bug.cgi?id=1183652
- It turned out to be a `fbiterm` issue, it can be reproduced with a simple `fbiterm vim` command
- The workaround is to set `TERM=vt100`
- Improved `shell` in GUI (Qt)
- The previous fix to avoid "cannot set terminal process group" error messages printed by `bash`
was to use `dash` instead (see PR #934)
- But it turned out that `dash` is very limited, for example it does not suport <Tab> auto completion so it is quite
difficult to use it as an interactive shell
- The fix is to run `bash` but in a separate `xterm` window so it can activate the job control correctly
> Expert console: fixed "shell" command

- package/yast2-installation.changes
- src/lib/installation/clients/inst_disks_activate.rb
- src/lib/installation/clients/inst_network_check.rb
- src/lib/installation/clients/inst_update_installer.rb
- test/inst_disks_activate_test.rb
> When user presses Abort button on Network settings page, it works same way as "Back" button and returns to the previous dialog. — https://bugzilla.suse.com/show_bug.cgi?id=1183586
As stated in the [second comment](https://bugzilla.suse.com/show_bug.cgi?id=1183586#c2), this happens
>  because the network **subworkflow** should not use [Abort] (...) It should be possible to **abort only in the main workflow**.
To use an installation argument (`hide_abort_button`) when calling the _inst\_lan_ client to force it hiding the abort button during the installation. **See https://github.com/yast/yast-network/pull/1195** for more details.
> Hide the abort button when calling the network client

- package/yast2-installation.changes
- package/yast2-installation.spec
Wrongly changed at https://github.com/yast/yast-installation/pull/937 but detected at https://ci.opensuse.org/job/yast-yast-installation-master/154/console
> Fix version and changelog

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F08-logging
- https://bugzilla.suse.com/show_bug.cgi?id=1184491
- YaST displays a "Terminated" error message at the very end
- It is harmless but it looks awkward
- Fixed by starting the `memsample` tool in a subshell, the main shell process is then not connected to the `memsample` process and it does not care about it's termination status
> Avoid "Terminated" message displayed at the end (bsc#1184491)

- bin/memsample-csv-plot
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_cleaner.rb
This tries to consolidate all the recent contributions in a single pull request that is easy to review:
- #943 was nice to review, but lacked the changes in #940 
- #940 lacked the changelog entry and was closed in favor of #939 (which had its own problems)
- #939 was hard to review and included some side effects like the removal of a `BuildRequires:  yast2-bootloader` that was pretty hard to spot and likely not wanted.
So this PR should bring the good parts of #943 and #940, without the extensive cleanup of #939.
> Fixes for tumbleweed

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/security_proposal.rb
- src/lib/installation/security_settings.rb
- src/lib/installation/widgets/polkit_default_priv.rb
- test/lib/clients/security_proposal_test.rb
- test/lib/widgets/polkit_default_priv_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1184277
- Use empty string instead of 'default' as the 'Default' id being shown correctly in the proposal when there is no polkit_default_privs selected in the profile.
> Use empty string instead of 'default' as the 'Default' id

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/dialogs/ntp_setup.rb
- test/lib/dialogs/ntp_setup_test.rb
We have been preparing the drop of **Yast::LanItems** adapting the some code in network which is still used by this module so we need to adapt it to.
- see https://github.com/yast/yast-network/pull/1216
- https://bugzilla.suse.com/show_bug.cgi?id=1185338
- Drop Yast::LanItems dependency completely.
> Drop Yast::LanItems dependency

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F08-logging
Cherry-pick #941 from yast/memsample_terminated for SP3 (MU)
- https://bugzilla.suse.com/show_bug.cgi?id=1184491
> Avoid "Terminated" message displayed at the end (bsc#1184491) (SP3)

- bin/memsample-csv-plot
- doc/memory-profile-valgrind-massif.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- https://bugzilla.suse.com/show_bug.cgi?id=1182649
- https://trello.com/c/oj8K4EPu
Allow memory profiling of the main installer process, via  boot parameters: 
- MASSIF=1 enables Valgrind/Massif (C/C++ level)
- MEMORY_PROFILER=1 enables Ruby level
see [doc/memory-profile-valgrind-massif.md](https://github.com/yast/yast-installation/blob/44835c83560a9820df424ca88cc0f32c90e5abbf/doc/memory-profile-valgrind-massif.md)
The necessary packages need to be present:
- Massif is pulled in with `extend=gdb`, done by https://github.com/openSUSE/installation-images/pull/506 (merged)
(to test this before i-i is updated, extract /usr/bin/debuginfod-find from a TW debuginfod-client.rpm and copy it to a live inst-sys)
- memory_profiler.gem is TODO
> Optional in-process memory profiling: MEMORY_PROFILER=1 and MASSIF=1

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
Backport #872 to fix [bsc#1174194](https://bugzilla.suse.com/show_bug.cgi?id=1174194).
* Moving <files> section handling to the first installation stage.
* See https://github.com/yast/yast-autoinstallation/pull/760
* Trello: https://trello.com/c/jgBnBQOU/
> Backport handling of <files> section in 1st stage

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
It could take some time until the X Server is ready and it could be even open to an infinite loop. While we are waiting a blank screen is shown without any hint about what is going on.
- https://trello.com/c/4DpZZook/2441-3-osdistribution-p3-1185095-auto-installation-stalls-at-start-of-stage-2-icewm-package-not-installed
Fallback to **ncurses** in case that open a X display fails after 15 attempts / seconds. In case of **VNC** the loop will maintained until success by now.
> Do not try to open a X display forever (bsc#1185095)

- bin/yupdate
- https://bugzilla.suse.com/show_bug.cgi?id=1183795#c21
- The default overlay list includes the `/usr/lib64/YaST2` directory but that does not exist on 32-bit systems and it fails.
- If the target directory does not exist do not try creating an overlay for it, just skip it.
- Technical note: `File.writable?` returns `false` for non-existing paths, you have to explicitly check that the directory exists to catch this case.
> yupdate: Do not create overlays for non-existing directories

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/select_system_role.rb
- src/lib/installation/system_role.rb
- test/system_role_test.rb
There is no way to influence IP forwarding defaults settings during installation, something that would be nice to be have (see https://github.com/yast/yast-network/pull/1229)
- https://bugzilla.suse.com/show_bug.cgi?id=1186280
- https://trello.com/c/Jao9dDKQ/2477-5-make-forwarding-configurable-for-installer
- Modify IP forwarding network configuration using the defaults defined in the control file when a new role is selected.
It depends on yast/yast-network#1229
> Allow to set IP forwarding defaults through the control file (bsc#1186280)

- .rubocop.yml
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/upgrade_repo_manager_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1185822
- During migration usually the new repositories have a different URL so they point to new package versions (e.g. the Basesystem Module for SLE15-SP2 is replaced with SLE15-SP3 repository with different name and URL)
- During migration YaST offers to remove the old repositories because the old repositories/packages could potentially cause conflicts or other dependency problems
- But the detection of the old repositories does not work properly if the new repository is the same as the old one (X replaced by X), in that case the repository looks like as if it was old and should not be used anymore
- The improved code loads the current (SP3) registered repositories and these repositories are excluded from the old ones
- Tested manually, see …
> [SP3] Improve evaluating the old repositories (bsc#1185822)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/proxy_finish.rb
- startup/common/misc.sh
- test/lib/clients/proxy_finish_test.rb
- test/test_helper.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1185016
- https://trello.com/c/s9gfK64m/2499-sles15-sp2-p2-1185016-l3-autoyast-does-not-set-proxy-properly-ref00d1iglod5001ixjkyhref
During installation, the installation fails if http and https traffic is restricted allowing only connnections through a proxy. The current proxy settings export the **http_proxy** variable but not the **https_proxy** which is used for downloading the online updates.
- https://github.com/yast/yast-packager/blob/master/src/lib/y2packager/clients/inst_productsources.rb#L482
Related: 
- https://bugzilla.suse.com/show_bug.cgi?id=305163
- https://bugzilla.suse.com/show_bug.cgi?id=923788
- https://bugzilla.suse.com/show_bug.cgi?id=869640 (remove old inst_network_setup.rb client)
Export also the **https_proxy** variable …
> Write proxy settings at the end of the First Stage and export https_proxy

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_pre_install.rb
- test/ssh_import_auto_test.rb
> For some reason, the scope resolution operator in ::Users::UsersDatabase
was forgotten/omitted in #371, but it is needed to avoid resolving to Yast::Users::UsersDatabase.
> Fix ::Users::UsersDatabase call

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/security_settings.rb
- test/lib/security_settings_test.rb
*yast2-users* code is being adapted to use *shadow tools*. This module uses some API methods that are going to be dropped in favor of new `Y2Users` classes.
Adapt code to use the new `Y2Users` classes.
NOTE: this PR should not be merged yet. It requires [*yast-users/y2users*](https://github.com/yast/yast-users/tree/y2users) branch to be merged before.
* Unit tests adapted
* Manually tested
> Adapt to Y2Users

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/prep_shrink.rb
When shrinking a PReP partition, the resulting partition is not correctly aligned according to the block size. The problem comes from the *end* value passed to the *parted resize* command. *Parted* tries to align the end of the partition. But, for some reason, the resulting alignment is not correct. 
* https://bugzilla.suse.com/show_bug.cgi?id=1186371
Avoid *parted* misalignment by indicating a proper end of the partition in KiB unit. 
Note: The current logic for shrinking a PReP partition always expects to find the PReP partition at the beginning of the disk. 
~~It was not possible to reproduce this bug in a ppc64le virtual machine (qemu). A disk with 8 KiB system and logical block sizes was used, as in the scenario of the reported bug.~~
As [Steffen …
> Ensure PReP partition alignment

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_disks_activate.rb
- test/inst_disks_activate_test.rb
Storage devices are not activated before probing, see https://github.com/yast/yast-installation/commit/f6b5e9efb7cbc8074f94ca2613cd55fed7fbfb15.
* https://bugzilla.suse.com/show_bug.cgi?id=1187220
Add missing call for activating devices.
> Activate devices

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
- test/lib/clients/inst_download_release_notes_test.rb
- During upgrade the `Release Notes` button is not displayed.
- It turned out that the `inst_download_release_notes` client is called but it exits early, it does not even try downloading the release notes at all.
- The `Packages.Init` call is not used during upgrade and the [test at the beginning](https://github.com/yast/yast-installation/blob/0a258deb0d516a606fa9ea5962c80947063a6b42/src/lib/installation/clients/inst_download_release_notes.rb#L80) is always evaluated to `false` resulting in immediate exit without doing anything
- The upgrade process [only calls some parts](https://github.com/yast/yast-registration/blob/160c236de58b72505ce29acad8dfbaaed2878775/src/lib/registration/ui/migration_repos_workflow.rb#L737-L743) of the `Packages.Init` from outside (esp. …
> Display release notes during upgrade (bsc#1186044)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/pre_umount_finish.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1189793
- Close the libzypp cache to allow cleanly unmounting `/mnt/var/cache/zypp` directory
- I have manually tested with the debugger that after calling `Pkg.SourceFinishAll` the `/mnt/var` directory can be cleanly unmounted:
- Tested manually with patched installer (using `yupdate`), the `y2log` did not contain any error and the `/mnt/var` directory was cleanly unmounted.
> Close the libzypp cache (bsc#1189793)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/proposal_runner.rb
- https://trello.com/c/Bnc4V82U
- https://bugzilla.suse.com/show_bug.cgi?id=1190294 (L3Q)
Filter the installation proposals (in the Installation Settings screen) according to the AutoYaST profile even before tab switching 
The filtering code was only used after a tab change (in `switch_to_tab`), here apply it also for the initial display.
I tested the fix with a profile that limited the proposals to *software* and *language*:
```xml
<profile xmlns="http://www.suse.com/1.0/yast2ns"
xmlns:config="http://www.suse.com/1.0/configns">
<general>
<mode>
<confirm config:type="boolean">true</confirm>
</mode>
<proposals config:type="list">
<proposal>software_proposal</proposal>
<proposal>language_proposal</proposal>
</proposals>
</general>
...
```
(full profile at …
> Fix displaying a custom proposal set in AY

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_download_release_notes.rb
- src/lib/installation/update_repository.rb
- test/lib/clients/inst_download_release_notes_test.rb
- test/update_repository_test.rb
Displays an error message when retrieving the release notes caused an error. See https://github.com/yast/yast-yast2/pull/1205.
> Handle release notes error

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- src/lib/installation/clients/inst_system_analysis.rb
- test/copy_files_finish_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1193339
- The `subscription-tools` package is not present in SLE15 anymore
- 4.4.25
> Drop support for subscription-tools (bsc#1193339)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- src/lib/installation/dialogs/complex_welcome.rb
- src/lib/installation/widgets/product_selector.rb
- test/lib/clients/inst_complex_welcome_test.rb
- test/lib/dialogs/complex_welcome_test.rb
- test/lib/widgets/product_selector_test.rb
This PR fixes [bsc#1193223](https://bugzilla.suse.com/show_bug.cgi?id=1193223) and [bsc#1192230](https://bugzilla.suse.com/show_bug.cgi?id=1192230).
* When a single product is found, preselect the product and show the license.
* When a single product is found *during upgrade* and the license is not available, do not try to show the license.
Trello:
* https://trello.com/c/fhSncPcg/
* https://trello.com/c/jAaewORI/
- Tests
> Fix complex welcome

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/update_repositories_finder.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1193536
- Do not scan the installation repository for the self update products, it takes very long time on the SLE Full medium
- Updated documentation
- See more details in https://github.com/yast/yast-registration/pull/552
> Self-update: do not scan the installation medium (bsc#1193536)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/snapshots_finish.rb
- test/snapshots_finish_test.rb
Backport fix for [bsc#1180142](https://bugzilla.suse.com/show_bug.cgi?id=1180142) to SLE 12 SP3. Please, check #901 for details about the original fix.
Related to:
* https://github.com/yast/yast-yast2/pull/1211
* https://github.com/yast/yast-update/pull/176
> Backports fix for bsc#1180142 to SLE 12

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_complex_welcome.rb
- test/lib/clients/inst_complex_welcome_test.rb
PR #999 introduced a change to preselect the product when just a single one is available. However, this behavior should be avoided during upgrades. See [comment 25 on bsc#1192230](https://bugzilla.suse.com/show_bug.cgi?id=1192230#c25).
> bsc#1192230: do not preselect during upgrade

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/security_settings.rb
- test/lib/clients/security_proposal_test.rb
- test/lib/security_settings_test.rb
Do not propose **Linux Security Module** default configuration when it is declared as **not configurable** avoiding the write of the **kernel boot parameters** when are not needed / wanted. For more details see https://github.com/yast/yast-security/pull/117
> Do not propose Linux Security Module default config when declared as not configurable

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/ssh_import_auto.rb
- test/inst_update_installer_test.rb
- test/lib/clients/inst_complex_welcome_test.rb
- test/lib/clients/security_finish_test.rb
- test/lib/security_settings_test.rb
- test/lib/update_repositories_finder_test.rb
- test/lib/widgets/online_repos_test.rb
- test/lib/widgets/system_role_reader_test.rb
- test/proposal_runner_test.rb
- test/ssh_import_auto_test.rb
- test/test_helper.rb
- Fixed crash when importing an SSH configuration in AutoYaST installation
- 4.4.35
> Enable RSpec verifying doubles in unit tests (bsc#1194784)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/upgrade_repo_manager_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1194453
- Do not delete the new services which have the same name as an old service
- Related to https://github.com/yast/yast-yast2/pull/1239 and https://github.com/yast/yast-registration/pull/562
> Handle service name collision during upgrade (bsc#1194453)

- bin/memsample
- package/yast2-installation.changes
- package/yast2-installation.spec
- Redirect the STDERR output in the memsample script to not break the YaST UI
- See https://bugzilla.suse.com/show_bug.cgi?id=1195116#c8
- 4.4.38
> Memsample: redirect the STDERR output (bsc#1195116)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/console.rb
- Fixed crash after pressing the hamburger menu icon in the welcome screen
- Regression in Ruby 3.1
- https://bugzilla.suse.com/show_bug.cgi?id=1195422
Just run the `require "irb"` command earlier.
Tested manually in the latest TW installer, the expert console dialog it now correctly displayed.
> Expert console: fixed crash in Ruby 3.1 (bsc#1195422)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
Qt 5.15 (actually, 5.14) introduces a behavior change with respect to hidpi screens and it now needs Xft.dpi to be set in order to use it. This change uses xrandr to find out edid information and xrdb to set Xft.dpi accordingly when starting the X server in YaST2.call. It always sets dpi to multiples of 48 with a minimum of 96 and a maximum of 288 (being effectively the same as having zoom factors of 1x, 1.5x, 2x, 2.5x amd 3x). Higher (or lower) dpi values are not used in order to try to filter out monitors that return wrong edid values.
> Set the Xft.dpi resource to fix small fonts in hidpi screens

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/security_proposal.rb
YaST should not add verbs to the installation summary. In the case of **AppArmor**, just show that without the activate, and only show **None** when nothing will be applied/set.
- https://bugzilla.suse.com/show_bug.cgi?id=1196013
> Adjusted Linux Security Module installation summary labels

- doc/snapshots.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/snapshots_finish.rb
- test/snapshots_finish_test.rb
Feature [SLE#25560](https://jira.suse.com/browse/SLE-22560).
Trello: https://trello.com/c/RovP5dk3/
On systems using the transactional-update mechanism, the filesystem is supposed to be mounted as read-only at the end of the installation. In those cases, we should not create a snapshot.
In this attempt, we check the mount options in the storage staging devicegraph.
> SLE#25560: do not create a snapshot after install/upgrade if root filesystem is RO

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
**AutoYaST init-scripts** are run before **systemd-user-sessions.service** which prevent users including privileged ones to login the system which in case of **ssh** installation does not allow the user to connect until pam_systemd gives a timeout.
- https://bugzilla.suse.com/show_bug.cgi?id=1195059
Adapted the service file as suggested being run just after systemd-user-sessions.service.
> Fix Second Stage timeout when using ssh (bsc#1195059)

- bin/memsample-archive-to-csv
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- startup/YaST2.ssh
- https://bugzilla.suse.com/show_bug.cgi?id=1196287
- The `installation_slim` theme does not exist anymore, after merging https://github.com/yast/yast-yast2/pull/1242 it is not changed to the default theme. If theme does not exist then the default (light) Qt theme is used.
- Additionally fixed crash is the `memsample-archive-to-csv` script, related to https://github.com/yast/yast-installation/pull/1017
Tested manually, with the fix it uses the usual default installation style:
> SSH installation theme fix

- startup/common/vnc.sh
With the update to tigervnc 1.12.0.
Xvnc no longer supports -rfbwait parameter.
This should fix bsc#1196201.
With older Xvnc versions, -rfbwait default value is 30 seconds. 
That shouldn't be a problem.
> Drop -rfbwait parameter on Xvnc

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/console/commands.rb
- The `respond_to_missing?` method actually accepts *two* arguments!
- See an [example](https://ruby-doc.org/core-3.1.1/BasicObject.html) in the documentation
- That is valid for both [Ruby 2.5](https://ruby-doc.org/core-2.5.9/Object.html#method-i-respond_to_missing-3F) (SLE15) and [Ruby 3.1](https://ruby-doc.org/core-3.1.1/Object.html#method-i-respond_to_missing-3F) (Tumbleweed)
Tested manually
| Original Code | Fixed |
|----|----|
| ![expert_console_crash](https://user-images.githubusercontent.com/907998/156632022-0ab3c9e4-f9b9-4538-9fc7-64039101e04c.png) | ![expert_console_fixed](https://user-images.githubusercontent.com/907998/156632039-b37ec04e-aed8-4802-912d-938760335852.png) |
> Fixed crash when starting the expert console (bsc#1196724)

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
When running *YaST2-Second-Stage.service*, if you switch to a virtual console (e.g., ctrl + alt + F1), then getty prompt is shown. Before changes introduced by https://github.com/yast/yast-installation/pull/1024, *systemd-user-sessions.service* was forced to run after the second stage (actually, after the *autoyast-initscripts.service*). This prevented getty prompt while switching to a virtual console. Now, *systemd-user-sessions.service* runs before the second stage. So, [*systemd-getty-generator*](https://www.freedesktop.org/software/systemd/man/systemd-getty-generator.html) is able to instanciate a getty service when switching to a virtual console.
Note that *YaST2-Second-Stage.service* set `Before=getty-pre.target`, but this is not enough to avoid *systemd-getty-generator* …
> Avoid login

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- [bsc#1196614](https://bugzilla.suse.com/show_bug.cgi?id=1196614)
- https://trello.com/c/yLz1DrJp
Dependencies in *YaST2-Second-Stage.service* have been adjusted. First, it was necessary to force the second stage service to run after *systemd-user-sessions.service* in order to avoid issues when connecting with ssh, see https://github.com/yast/yast-installation/pull/1024. Then, that patch was improved to avoid display manager and getty prompt to appear too early, see https://github.com/yast/yast-installation/pull/1030.
With the latest changes, it is still possible to switch to another virtual console (ctrl+alt+f2-6), making *systemd-getty-generator* to instantiate a getty service on demand. Note that getty auto-generation is prevented if *systemd-user-sessions.service* runs after YaST …
> Prevent getty auto-generation

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
If **purge-kernels** does not finish before **YaST2-Second-Stage** is run it locks **zypper** and a nasty message is shown. For preventing this situation YaST2-Second-Stage should be run after the **purge-kernels.service**.
- https://bugzilla.suse.com/show_bug.cgi?id=1196431 (https://trello.com/c/tl491wU2)
Adapt **YaST2-Second-Stage.service** to be fun after **purge-kernels.service**
> Run YaST2-Second-Stage after purge-kernels service

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/Second-Stage/S09-cleanup
- startup/YaST2.call
- startup/common/misc.sh
- During the Second Stage of an installation, the **xvnc.socket** can starts before the **YaST2-Second-Stage** service runs its own Xvnc server. That could produce a black screen vnc connection as reported by openQA.
- In the past (see [yast/yast-installation: Pull Request 316](https://github.com/yast/yast-installation/pull/316)) we used to have a **systemd dependency** to be run before **xinetd** service and we removed that because some cycle dependency but once we removed **xinetd** it looks safer to add a before **xvnc.socket** dependency instead of stop the service and run it again which looks strange.
- https://bugzilla.suse.com/show_bug.cgi?id=1197265 (https://trello.com/c/cl2XRuwf/)
Add **Before=xvnc.socket** to **YaST2-Second-Stage** and **YaST2-Firstboot** services. This will …
> Add Before=xvnc.socket dependency to Firstboot and Second Stage services (bsc#1197265)

- package/YaST2-Firstboot.service
- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/Second-Stage/S09-cleanup
- startup/YaST2.call
- startup/common/misc.sh
This reverts commit 0f3456341afa58b6265fe9217a0ccfcce975ecf9.
Our recent changes in the services (start after **systemd-user-sessiones** #1024 and after **purge-kernels** #1036) probably introduced a bigger window time to connect to the **xvnc.socket** instance getting a black screen... specially the change about starting after the purge of old kernels will delay the start of our services. 
We tried to fix that (see https://bugzilla.suse.com/show_bug.cgi?id=1197265) adding a **Before=xvnc.socket** dependency which is the behavior we would like to have but as **Frank Bui** explained **YaST2-Second-Stage** and **YaST2-Firstboot.service** can't have **DefaultDependencies=yes** (implicit setting, which implies **After=basic.target**) and in the meantime has **Before=xvnc.socket** (which is …
> Revert "AY: Do not stop xvnc.socket but rely on systemd"

- package/yast2-installation.changes
- package/yast2-installation.spec
The system hangs when it is updated by the initscripts service and it contains an updated version of this package.
- https://bugzilla.suse.com/show_bug.cgi?id=1199480
- https://bugzilla.suse.com/show_bug.cgi?id=1200274
Do not restart yast2-installation services when the package is updated. 
**Note:** It will not help if the system is updated with previous versions of the package but will help with future ones.
Tested manually
> Do not restart services when the package is updated

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- `yast2-installation` depends on `xrdb`, that has two negative consequences
- `xrdb` depends on some X libraries and because `yast2-installation` is included in the installed system then the X libraries are installed even in a minimal text mod installation
- it also depends on the C pre-processor which has ~22MB (!)
- Use an YaST specific tool instead of `xrdb` (see https://github.com/yast/yast-x11/pull/25), it does not depend on `cpp`
- Install the `yast2-x11` package only when `libyui-qt` is installed, otherwise it does not make sense
The "new" expressions in RPM dependencies are supported since rpm 4.13. This is used in SUSE since 2017, SLE15-GA contains rpm 4.14.1 so this is supported even in the first SLE15 release. See more details in …
> Do not use "xrdb" for setting the "Xft.dpi" value (bsc#1201532)

- package/YaST2-Second-Stage.service
- package/yast2-installation.changes
- package/yast2-installation.spec
In order to prevent a ssh timeout produced because of systemd logind we [added](https://github.com/yast/yast-network/pull/1024) a condition to run the **SecondStage.service** after  **systemd-user-sessions** but once syste systemd logind has been patched (see https://github.com/systemd/systemd/pull/23936 & https://build.suse.de/request/show/276157) our fix can be reverted removing 
the Before condition.
- https://bugzilla.suse.com/show_bug.cgi?id=1200780 & https://bugzilla.suse.com/show_bug.cgi?id=1195059
Remove the **After=systemd-user-sessions** condition from the YaST2-SecondStage.service once systemd logind has been patched to prevent the ssh timeout.
> Before user sessions

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
- Backport #1052 to SP4
- https://bugzilla.suse.com/show_bug.cgi?id=1201966#c5
> [SP4] Do not use "xrdb" for setting the "Xft.dpi" value (bsc#1201966, bsc#1201532)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/YaST2.call
The last PR https://github.com/yast/yast-installation/pull/1057 changed the font size even in non-HiDPI cases ever so slightly, so the existing openQA needles don't fit anymore.
The two environment variables were always set, even for a scale factor of 1:
```
QT_SCALE_FACTOR=1
QT_SCALE_FACTOR_ROUNDING_POLICY="PassThrough"
```
which obviously does make a difference.
Only set them if > 1.
> Avoid Recreating all openQA Needles

- src/lib/installation/clients/security_finish.rb
- test/lib/clients/security_finish_test.rb
Replace `#write_config` with `#write` to conform to the changes in https://github.com/yast/yast-security/pull/142.
> Replace SecurityPolicies::Manager#write_config with #write

- package/yast2-installation.changes
- src/lib/installation/proposal_store.rb
In theory, the different proposal clients displayed in the installation summary have the option to incorporate their own help texts to the general help of the summary screen.
That's documented in the [`Installation::ProposalClient`](https://github.com/yast/yast-yast2/blob/master/library/general/src/lib/installation/proposal_client.rb) class.
Unfortunately, the whole mechanism seems to be rather broken:
- The help texts of the clients are simply being ignored at least since the introduction of https://github.com/yast/yast-installation/pull/279 (at 2015!)
- The mentioned documentation at `ProposalClient` is also wrong. According to the current (broken) code, the help is fetched from the `description` hash, not from the `make_proposal` one (as documented).
- Nobody noticed it because there …
> Fix generation of help text in the installation summary

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
- https://trello.com/c/CAytlL3W
- https://jira.suse.com/browse/SLE-22578
- https://jira.suse.com/browse/SLE-24584
Add URI schema that works relative to the installation medium. Also, unify the URI schemes so that the Zypp/Addon syntax also works with AutoYaST.
Note that `relurl` cannot be used as it already has the meaning of 'relative to the AutoYaST profile' in AutoYaST context.
So, a new `repo` scheme is introduced.
- https://github.com/openSUSE/linuxrc/pull/299
- https://github.com/yast/yast-yast2/pull/1276
- https://github.com/yast/yast-autoinstallation/pull/852
> add 'repo', 'cd', and 'hd' schemes to Yast::Transfer::FileFromUrl

- README.md
- doc/url.md
Document current state of URL handling in the installer.
- https://trello.com/c/CAytlL3W
Usage:
- https://github.com/yast/yast-packager/pull/624
- https://github.com/yast/yast-add-on/pull/127
> document installer URL usage

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/security_finish.rb
- test/lib/clients/security_finish_test.rb
Security policies and rules can be enabled/disabled during the (auto-)installation. That info has to be transfered to the config file of the script provided by the ssg-apply package.  
For more info, see:
* https://github.com/yast/yast-security/pull/128
* https://github.com/yast/yast-security/pull/137
Adapt *security_finish* client to also write the security policies config.
* Added new unit tests
* Tested manually
> Security policy

- package/yast2-installation.changes
- package/yast2-installation.spec
- test/lib/clients/inst_download_release_notes_test.rb
- test/system_role_test.rb
- https://bugzilla.opensuse.org/show_bug.cgi?id=1204871 "- [Staging] rubygem-rspec-* 3.12 breaks various yast modules build"
- see https://github.com/yast/yast-yast2/pull/1279 for details
> Fix hash vs keyword arguments in RSpec expectations (bsc#1204871)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/common/vnc.sh
https://bugzilla.suse.com/show_bug.cgi?id=1205585
On installations using Xvnc, sometimes the font rendering is broken in the Qt UI to the point of making some fonts illegible.
_See the wizard steps on the left side._
@Vogtinator found out that there is a bug in the Qt libs:
https://bugreports.qt.io/browse/QTBUG-109169
> It's a bad conversion between QRgb and QRgba64 types in a gamma correct blending function. 
@Vogtinator also suggested to drop using the `-depth 16` option when starting `Xvnc` to avoid getting into that special case. That's what this PR does.
> Use default Depth for Xvnc

- bin/yupdate
- doc/yupdate.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- test/yupdate/inst_sys_test.rb
The current `yupdate` script can be only used from inst-sys for patching the standard YaST modules. It would be nice to extend it so it could be used the same way with the D-Installer. This would make testing and development of new features easier.
Adapt the script so it can work in a different environment (live medium).
- Check for the live medium environment (the root uses the `overlay` file system)
- Do not try to modify `/etc/install.inf` if it does not exist (it is not present on the live medium)
- Add pre and post hooks so some actions can be done before patching the system (installing some RPM packages) or after (restarting the DBus service). It runs the `.yupdate.pre` and `.yupdate.post` scripts when present in the source code.
- Updated unit test
> yupdate - allow patching the D-Installer

- bin/yupdate
- package/yast2-installation.changes
- package/yast2-installation.spec
- test/yupdate/system_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1207069
- The yupdate script refuses to work in a container, that should be allowed.
- Detect a container presence with `systemd-detect-virt --container`, fallback to testing some container specific files.
- If a container is detected then allow patching the system.
```
yast-container PC:/ # yupdate patch yast/yast-packager master
Downloading https://github.com/yast/yast-packager/archive/master.tar.gz
Preparing files...
Copying to system...
Updated: /usr/share/YaST2/include/checkmedia/ui.rb
Updated: /usr/share/applications/YaST2/org.opensuse.yast.CheckMedia.desktop
Updated: /usr/share/applications/YaST2/org.opensuse.yast.SWSingle.desktop
Updated: /usr/share/applications/YaST2/org.opensuse.yast.SWSource.desktop
Updated: …
```
> yupdate - added suport for patching containers (bsc#1207069)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/include/installation/inst_inc_all.rb
When **linuxrc** (see https://github.com/openSUSE/linuxrc/pull/310) detects that there is some NBFT configured interface it will sets the **UseNBFT** variable and we should YaST should call `nvme connect-all` in order to discover and connect to all discovered **NVMe-over-Fabrics subsystems**
- https://trello.com/c/eFJXEeep/3274-3-urgent-top-priority-connect-to-nbft-disks
- https://jira.suse.com/browse/PED-967
- https://jira.suse.com/browse/PED-3118
It was decided to add the call where we evaluate if the disks activation client should be disabled or not, currently we will just capture **Cheetah** exceptions and log that there were were some problem connecting **NVMe-oF subsystems** but as the **UI** is not completely initialized at that point we will not report any issue to the user.
In …
> Connect to all discovered NVMe-over-Fabrics subsystems in case of UseNBFT (jsc#PED-967)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/include/installation/inst_inc_all.rb
It was requested to use `nvme connect-nbft` when **UseNBFT** was set by **linuxrc** but we call  `nvme connect-all`.
- https://trello.com/c/eFJXEeep/3274-3-urgent-top-priority-connect-to-nbft-disks
- https://jira.suse.com/browse/PED-3138
- https://build.suse.de/request/show/288814
Implement the call as requested (it depends on https://build.suse.de/request/show/288814)
> Connect only nbft

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
- test/file_from_url_test.rb
Backport #982 to the `SLE-15-SP2` branch.
The problem was introduced when moving the processing of the `<files>` section from the 2nd to the
1st stage (see #760).
> Fix file:// and relurl:// scheme copy

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/security_proposal.rb
- File `security_proposal.rb` had executable flag set, it is not needed there
- Also removed the shebang (not needed) and the UTF-8 mark (Ruby default anyway)
- See more details in related https://github.com/yast/yast-storage-ng/pull/1322
> [SLE15-SP5] Removed unnecessary executable flag (bsc#1209094)

- bin/yupdate
- package/yast2-installation.changes
- package/yast2-installation.spec
- The latest Agama Live ISO uses different Kiwi options and the Live ISO now uses disk mapper instead of the Overlay FS to make the root writable
- As the Live ISO implementation can change in the future again let's add the `--force` option which can skip the system detection 
> yupdate - improved Live ISO detection, added "--force" option

- bin/yupdate
- package/yast2-installation.changes
- package/yast2-installation.spec
- Patching the Agama installer does not work properly
- It fails because the pre/post scripts are not executed
- It turned out that the GitHub tarballs have all content in a `<repo>-<branch>` subdirectory, e.g. `agama-master`
- When downloading from GitHub add this extra path so the files are correctly found
> Fixed yupdate script (bsc#1213197)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_upgrade_urls.rb
From the bug description:
What happened prior to Leap 15.3 was the Toggle Status button cycled through three options: Delete, Keep, and Disable. For Leap 15.4 and 15.5, The displayed options are only Delete and Keep. However, there are still three states, as repeatedly pressing Toggle Status will show you. First press of Toggle Status changes the display to Keep; second press the display stays Keep; third press the display returns to Delete.
- [bsc1213959](https://bugzilla.suse.com/show_bug.cgi?id=1213959)
- Most probably introduced in this commit 661f8f5d6e450aff5727f4b4c3b5cac9dd874624
Fixed symbols used for referencing to particular labels
Opensuse 15.4 and 15.5 affected. However impact is small so I propose it for tumbleweed only
- *Tested manually*
*If the fix affects the UI attach …
> Status toggling in the "Previously Used Repositories" dialog didn't work well

- package/yast2-installation.changes
- package/yast2-installation.spec
https://bugzilla.suse.com/show_bug.cgi?id=1214277
https://trello.com/c/bgfX60e4/
If `awk` is not installed, there are error messages on the console during a firstboot workflow.
Require `awk` in the spec file.
Explicitly using `awk` and not `gawk` (the GNU version of `awk`) so lighterweight alternatives like _busybox_ can be used if they provide the `awk` symbol (which _busybox_ currently does not).
Many are part of the _coreutils_ package which we already require. Others are so common that a Linux system has little chance of working when they are missing, such as `grep` or `sed`: A lot of other packages depend on them.
See also the discussion in the bug.
> Require awk for use in Startup Scripts

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_upgrade_urls.rb
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/clients/inst_upgrade_urls_test.rb
- test/lib/upgrade_repo_manager_test.rb
- Related to https://github.com/yast/yast-update/pull/191
- This fixes using the old repositories in openSUSE
- In SLE it works fine but the explicit refresh is better. Libzypp/pkg-bindings run autorefresh automatically using a timestamp, but on some systems without RTC (some Arm boards) it might be better to not rely on the correct current time and force the refresh
> [SLE15-SP5] Refresh repositories with changed URL and reload them again

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_upgrade_urls.rb
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/clients/inst_upgrade_urls_test.rb
- test/lib/upgrade_repo_manager_test.rb
- Just merging PR #1098  to master
- There is a small improvement, it uses the new `Repository.refresh` method
- See https://github.com/yast/yast-yast2/pull/1296
> [master] Refresh repositories with changed URL and reload them again

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
- test/file_from_url_test.rb
[bsc#1217637](https://bugzilla.suse.com/show_bug.cgi?id=1217637)
Retrieving an AutoYaST profile using an NFS share with an IPv6 address is impossible.
Enclose the IPv6 address within square brackets when calling the `mount` command.
* Unit-tested only.
* Manual test is pending.
> bsc#1217637: retrieve an AutoYaST profile on a NFS+IPv6 setup

- doc/SELF_UPDATE.md
- doc/installation_overview.md
- doc/memory-profile-valgrind-massif.md
- doc/url.md
- doc/yupdate.md
- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/transfer/file_from_url.rb
- test/file_from_url_test.rb
* Merge fix for [bsc#1217637](https://bugzilla.suse.com/show_bug.cgi?id=1217637) into `master` (see #1101).
* Adapt the documentation format according to https://github.com/lsegal/yard/issues/1422.
> bsc#1217637: retrieve an AutoYaST profile on a NFS+IPv6 setup (SLE-15-SP6)

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/cio_ignore.rb
- test/cio_ignore_test.rb
Change #1104 implementation writing the **cio_ignore kernel parameter** only if given according to the bug request. It depends on https://github.com/yast/yast-yast2/pull/1300
> In zVM || KVM write the cio_kernel_parameter only if given

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/upgrade_repo_manager.rb
- test/lib/upgrade_repo_manager_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1218391
- The upgrade summary from SLE12 does not list several modules and extensions
- From the y2log it turned out that the products were properly selected to install but later the package manager was restarted and the selected products were not restored back.
- Restore the selected products after reloading the package manager, properly install all products for new modules and extensions.
- Added a new unit test
The `upgrade_repo_manager.rb` file has not been changed since SP5 where the problem does not happen. But it was not called at all there, so the bug was triggered by some other change. Anyway restoring the previous selection after reloading the package manager it always a good idea.
The original buggy behavior, for …
> Restore the selected products (bsc#1218391)

- .github/workflows/submit.yml
We need to maintain the Jenkins jobs for submitting the package to openSUSE Factory. And someone needs to maintain the Jenkins instance for that.
- Let's try using the GitHub Actions to implement the same mechanism
- Move the common parts to a shared action
- Easier maintenance, we will need to touch just one place, not all YaST repositories
- The GitHub Action is then small and we can use the same definition everywhere
I already tested that in my fork (https://github.com/lslezak/yast-devtools/blob/master/.github/workflows/submit.yml), let's test that with some real YaST package.
- See https://github.com/yast/actions/blob/master/submit/action.yml
> Added GitHub Action for submitting the package to OBS Factory

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/include/installation/inst_inc_all.rb
When **linuxrc** (see [openSUSE/linuxrc#310](https://github.com/openSUSE/linuxrc/pull/310 "‌")) detects that there is some NBFT configured interface it will sets the **UseNBFT** variable and YaST calls `nvme connect-nbft` in order to discover and connect to all discovered **NVMe-over-Fabrics subsystems** as was [requested](https://github.com/yast/yast-installation/pull/1078 "‌") at implementation time.
As the nvme cli has been adapted supporting NBFT table the call should be also adapted calling `nvme connect-all --nbft` as requested in the bug and also as we can see in the [implementation PR description](https://github.com/linux-nvme/nvme-cli/pull/1791).
- https://bugzilla.suse.com/show_bug.cgi?id=1222246
Adapted the call as requested.
> Fix call for connecting all discovered NVMe-over-Fabrics subsystems (bsc#1222246)

- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/AUTHOR
- startup/YaST2.call
- startup/common/language.sh
https://bugzilla.suse.com/show_bug.cgi?id=1224053
https://trello.com/c/haqsYySu
We are using _fbiterm_ for much improved support for nontrivial locales like Chinese, Japanese, Korean in NCurses. But _fbiterm_ is part of the _xiterm_ package (it's the framebuffer version of _xiterm_, hence **FB**-**I**term) which has been abandoned upstream many years ago. With the upcoming GCC 14, it has build problems. The maintainer of the _xiterm_ package feels unable to continue supporting it; so we need to drop the _xiterm_ package and with it _fbiterm_.
- ~Don't require _xiterm_ in the YaST packages anymore.~
It turns out we never required _xiterm_ or _fbiterm_ in any YaST package: We always checked at runtime if `/usr/bin/fbiterm` was available and used it only if it was.
- Don't use `fbiterm` in …
> Drop fbiterm in Tumbleweed Installation

- bin/yupdate
Before: it would silently do nothing
(and I would wonder why my intent, `yupdate overlay create`, did not work)
Now: report an error, as intended
> Do report an error on `yupdate overlay`.

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
**This is for SLE-15-SP5**. A merge to SLE-15-SP6, -SP7 and master / Factory will follow.
https://bugzilla.suse.com/show_bug.cgi?id=1181625
https://trello.com/c/jxGwssL6/
In certain situations, an AutoYaST upgrade may block with a pop-up dialog "The system will reboot now" message that does not continue after a timeout as it should; the user needs to confirm it interactively which is against the idea of an auto-upgrade.
The pop-up is suppressed only in `Mode.autoinst`, not also in `Mode.autoupgrade`.
Instead of just checking for `Mode.autoinst`, check for `Mode.auto` which includes both `Mode.autoinst` and `Mode.autoupgrade`.
See also https://github.com/yast/yast-yast2/blob/master/library/general/src/modules/Mode.rb#L283-L286
- Merge to SLE-15-SP6: _TBD_
- Merge to SLE-15-SP7: _TBD_
- …
> Don't Block in AutoYaST Upgrade with Reboot Message [SLE-15-SP5]

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
**This merges #1119 to SLE-15-SP6.**  A merge to SLE-15-SP7 and master / Factory will follow.
https://bugzilla.suse.com/show_bug.cgi?id=1181625
https://trello.com/c/jxGwssL6/
In certain situations, an AutoYaST upgrade may block with a pop-up dialog "The system will reboot now" message that does not continue after a timeout as it should; the user needs to confirm it interactively which is against the idea of an auto-upgrade.
The pop-up is suppressed only in `Mode.autoinst`, not also in `Mode.autoupgrade`.
Instead of just checking for `Mode.autoinst`, check for `Mode.auto` which includes both `Mode.autoinst` and `Mode.autoupgrade`.
See also https://github.com/yast/yast-yast2/blob/master/library/general/src/modules/Mode.rb#L283-L286
- Original PR for SLE-15-SP5: #1119 
- Merge to SLE-15-SP7: …
> Don't Block in AutoYaST Upgrade with Reboot Message [SLE-15-SP6]

- doc/SELF_UPDATE.md
- package/yast2-installation.changes
Reported by L3, ptoptions need to use the "+" sign to "add" something as described in https://en.opensuse.org/SDB:Linuxrc#p_ptoptions
> Fixing the self_update documentation

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
**This is the _master_ / _Factory_ version of #1119 / #1120.** It was originally meant to be a merge of the SLE-15-SP7 / SP6 version, but this commit somehow got lost in the merging process; so this is a cherry-pick of that commit.
https://bugzilla.suse.com/show_bug.cgi?id=1181625
https://trello.com/c/jxGwssL6/
In certain situations, an AutoYaST upgrade may block with a pop-up dialog "The system will reboot now" message that does not continue after a timeout as it should; the user needs to confirm it interactively which is against the idea of an auto-upgrade.
The pop-up is suppressed only in `Mode.autoinst`, not also in `Mode.autoupgrade`.
Instead of just checking for `Mode.autoinst`, check for `Mode.auto` which includes both `Mode.autoinst` and `Mode.autoupgrade`.
See also …
> Don't Block in AutoYaST Upgrade with Reboot Message [master]

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/microos_role_dialog.rb
There is a crash in microos installation caused by the last change in #1125.
Fix the typo
- *Tested manually* using `rake run[inst_microos_role]` to verify that it will show proper dialog.
> Fix microos typo

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/copy_files_finish.rb
- test/copy_files_finish_test.rb
When there are multiple blacklisted modules then parsing does not work correctly and add it as single entry.
trello: https://trello.com/c/YrsSjjRG/3860-1231313-brokenmodulesab-results-in-invalid-blacklist
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1231313
Make parsing more robust regarding spaces around comma.
- *Added a new unit test*
> Fix brokenmodules

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/instsys_packages.rb
- test/instsys_packages_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1234661
- YaST displays a false alarm error, there is actually no problem with the self-update repository
- The problem was in reading the versions from the `/.packages.root` file, the package version additionally contains the architecture at the end
- When comparing versions the "4.6.5-150600.3.6.1" version from the self-update looks older as "4.6.5-150600.3.6.1.x86_64" from the inst-sys so then YaST complains about downgrade
- This happens only when the installation is booted from PXE using the updated `tftpboot-installation-*` packages (not the GA version, that works fine)
- Remove the architecture suffix from the version
- Updated unit test
- Tested manually by the SUMA team
> [SLE15-SP6] Fixed comparing versions in the self-update version check

- package/yast2-installation.changes
- package/yast2-installation.spec
- src/lib/installation/clients/inst_finish.rb
openqa needs a window to collect logs before reboot even in auto modes
Respect explicit reboot timeout on command line even in automatic modes.
- *Added a new unit test*
- *Tested manually*
*If the fix affects the UI attach some screenshots here.*
> Show dialog explicit

- doc/startup/firststage.tex
- doc/startup/stage.ps
- package/yast2-installation.changes
- package/yast2-installation.spec
- startup/First-Stage/F06-terminal
- startup/Second-Stage/S05-config
- startup/common/misc.sh
The package initviocons has problem to build and will be dropped from TW.
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1247578
Drop dependency and its usage as it is useful for obsolete and no longer supported hardware.
> Drop initviocons
